version: 20
services:
- name: postgres
  image: postgres:15
  envVars:
  - name: POSTGRES_PASSWORD
    value: postgres
  readinessCheckCommand: exec pg_isready -h 127.0.0.1 -p 5432
jobs:
- name: Build
  jobExecutor: onedev-executor-1
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:latest
    interpreter: !DefaultInterpreter
      commands:
      - dotnet nuget locals all -l
      - echo "{}" > TimeTracker.Tests.Integration.Api/appsettings.Local.json
      - echo "{}" > TimeTracker.Migrations/appsettings.Local.json
      - echo "{}" > TimeTracker.Tests.Integration.Business/appsettings.Local.json
      - echo "{}" > TimeTracker.Tests.Integration.Api/appsettings.Local.json
      - echo "{}" > TimeTracker.WorkerServices/appsettings.Local.json
      - ''
      - '# Tests'
      - dotnet build --configuration=Debug --output="./build/TimeTracker.Tests.Unit.Business"
        ./TimeTracker.Tests.Unit.Business
      - dotnet build --configuration=Debug --output="./build/TimeTracker.Tests.Integration.Business"
        ./TimeTracker.Tests.Integration.Business
      - dotnet build --configuration=Debug --output="./build/TimeTracker.Tests.Integration.Api"
        ./TimeTracker.Tests.Integration.Api
      - ''
      - '# Main projects '
      - dotnet build --configuration=Release --self-contained=false --runtime=linux-x64
        --output="./build/TimeTracker.Api" ./TimeTracker.Api
      - dotnet build --configuration=Release --self-contained=false --runtime=linux-x64
        --output="./build/TimeTracker.Migrations" ./TimeTracker.Migrations
      - dotnet build --configuration=Release --self-contained=false --runtime=linux-x64
        --output="./build/TimeTracker.Web" ./TimeTracker.Web
      - dotnet build --configuration=Release --self-contained=false --runtime=linux-x64
        --output="./build/TimeTracker.WorkerServices" ./TimeTracker.WorkerServices
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish artifacts
    artifacts: '*/**'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  paramSpecs:
  - !TextParam
    name: db
    allowEmpty: false
    multiline: false
    defaultValueProvider: !SpecifiedDefaultValue
      value: Some value
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  caches:
  - key: nuget-cache
    path: /root/.nuget/packages/
  timeout: 3600
- name: Run Integration Tests
  jobExecutor: onedev-executor-1
  steps:
  - !CommandStep
    name: Run migrations
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk
    interpreter: !DefaultInterpreter
      commands:
      - export ConnectionStrings__DefaultConnection="User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=postgres;Pooling=true;Include
        Error Detail=true;Log Parameters=true;"
      - export Hibernate__IsShowSql="false"
      - ''
      - ./build/TimeTracker.Migrations/TimeTracker.Migrations
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run Tests
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk
    interpreter: !DefaultInterpreter
      commands:
      - export ConnectionStrings__DefaultConnection="User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=postgres;Pooling=true;Include
        Error Detail=true;Log Parameters=true;"
      - export Hibernate__IsShowSql="false"
      - export Integration__ClickUp__SecurityKey="@secret:dev-integration-clickup-security-key@"
      - export Integration__Redmine__ApiKey="@secret:dev-integration-redmine-api-key@"
      - export Integration__Redmine__Url="@secret:dev-integration-redmine-url@"
      - export AWS__S3__AccessKey="@secret:dev-aws-s3-access-key@"
      - export AWS__S3__SecretKey="@secret:dev-aws-s3-secret-key@"
      - export AWS__S3__BucketName="@secret:dev-aws-s3-bucket-name@"
      - ''
      - 'ls -a '
      - ls -a build/
      - ls -a build/TimeTracker.Tests.Integration.Api/
      - ''
      - cd ./build/TimeTracker.Tests.Unit.Business/
      - dotnet test --logger trx --verbosity=minimal --results-directory /tmp/test
        ./TimeTracker.Tests.Unit.Business
      - ''
      - cd ./../TimeTracker.Tests.Integration.Business/
      - dotnet test --logger trx --verbosity=minimal --results-directory /tmp/test
        ./TimeTracker.Tests.Integration.Business
      - ''
      - cd ./../TimeTracker.Tests.Integration.Api/
      - dotnet test --logger trx --verbosity=minimal --results-directory /tmp/test
        ./TimeTracker.Tests.Integration.Api
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  paramSpecs:
  - !TextParam
    name: db
    allowEmpty: false
    multiline: false
    defaultValueProvider: !SpecifiedDefaultValue
      value: Some value
  triggers:
  - !PullRequestUpdateTrigger
    projects: TimeVic/Main
    params:
    - name: db
      valuesProvider: !Ignore {}
      secret: false
  jobDependencies:
  - jobName: Build
    requireSuccessful: true
    jobParams:
    - name: db
      valuesProvider: !SpecifiedValues
        values:
        - - Some value 2
      secret: false
    artifacts: '*/**'
  requiredServices:
  - postgres
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Publish
  jobExecutor: onedev-executor-1
  steps:
  - !CommandStep
    name: Build and push main docker image
    runInContainer: true
    image: docker
    interpreter: !DefaultInterpreter
      commands:
      - docker build -t lampego/timevic-main::@build_number@ . < devops/onedev/common/Dockerfile
      - ''
      - '# dockerhub-password is a job secret defined in "Settings / Build / Job Secrets" '
      - '# of the project'
      - '#docker login -u @secret:dockerhub-login@ -p @secret:dockerhub-password@'
      - docker push lampego/timevic-main::@build_number@
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  jobDependencies:
  - jobName: Build
    requireSuccessful: true
    jobParams:
    - name: db
      valuesProvider: !SpecifiedValues
        values:
        - - Some value
      secret: false
    artifacts: '*/**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
