version: 22
jobs:
- name: Build
  jobExecutor: onedev-executor-1
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk:latest
    interpreter: !DefaultInterpreter
      commands:
      - if [[ "@ref@" == "refs/heads/main" ]]; then
      - "\tconfiguration=\"Release\""
      - "\tenableWebAssemblyCompression=true"
      - else
      - "\tconfiguration=\"Development\""
      - "\tenableWebAssemblyCompression=false"
      - fi
      - ''
      - ''
      - dotnet nuget locals all -l
      - echo "{}" > TimeTracker.Tests.Integration.Api/appsettings.Local.json
      - echo "{}" > TimeTracker.Migrations/appsettings.Local.json
      - echo "{}" > TimeTracker.Tests.Integration.Business/appsettings.Local.json
      - echo "{}" > TimeTracker.Tests.Integration.Api/appsettings.Local.json
      - echo "{}" > TimeTracker.WorkerServices/appsettings.Local.json
      - ''
      - '# Tests'
      - dotnet build --configuration=Debug --output="./build/TimeTracker.Tests.Unit.Business"
        ./TimeTracker.Tests.Unit.Business
      - dotnet build --configuration=Debug --output="./build/TimeTracker.Tests.Integration.Business"
        ./TimeTracker.Tests.Integration.Business
      - dotnet build --configuration=Debug --output="./build/TimeTracker.Tests.Integration.Api"
        ./TimeTracker.Tests.Integration.Api
      - ''
      - '# Main projects '
      - dotnet build --configuration="$configuration" --self-contained=true --runtime=linux-x64
        --output="./build/TimeTracker.Api" ./TimeTracker.Api
      - dotnet build --configuration="$configuration" --self-contained=true --runtime=linux-x64
        --output="./build/TimeTracker.Migrations" ./TimeTracker.Migrations
      - dotnet build --configuration="$configuration" --self-contained=true --runtime=linux-x64
        --output="./build/TimeTracker.WorkerServices" ./TimeTracker.WorkerServices
      - ''
      - '# Web project'
      - '# -f net7.0'
      - dotnet publish -c "$configuration" -p:BlazorEnableCompression=$enableWebAssemblyCompression
        -r linux-x64 --self-contained=true --output="./build/TimeTracker.Web" ./TimeTracker.Web
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CreateTagStep
    name: Create Tag
    tagName: '@script:getTagName@'
    accessTokenSecret: dockerhub-login
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish artifacts
    artifacts: '*/**'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  caches:
  - key: nuget-cache
    path: /root/.nuget/packages/
  timeout: 3600
- name: Run Integration Tests
  jobExecutor: onedev-executor-1
  steps:
  - !CommandStep
    name: Run migrations
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk
    interpreter: !DefaultInterpreter
      commands:
      - export ConnectionStrings__DefaultConnection="User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=postgres;Pooling=true;Include
        Error Detail=true;Log Parameters=true;"
      - export Hibernate__IsShowSql="false"
      - ''
      - ./build/TimeTracker.Migrations/TimeTracker.Migrations
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run Tests
    runInContainer: true
    image: mcr.microsoft.com/dotnet/sdk
    interpreter: !DefaultInterpreter
      commands:
      - export ConnectionStrings__DefaultConnection="User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=postgres;Pooling=true;Include
        Error Detail=true;Log Parameters=true;"
      - export Hibernate__IsShowSql="false"
      - export Integration__ClickUp__SecurityKey="@secret:dev-integration-clickup-security-key@"
      - export Integration__Redmine__ApiKey="@secret:dev-integration-redmine-api-key@"
      - export Integration__Redmine__Url="@secret:dev-integration-redmine-url@"
      - export AWS__S3__AccessKey="@secret:dev-s3-access-key@"
      - export AWS__S3__SecretKey="@secret:dev-s3-secret-key@"
      - export AWS__S3__BucketName="@secret:dev-s3-bucket-name@"
      - ''
      - dotnet test --logger trx --verbosity=minimal --results-directory /tmp/test
        ./TimeTracker.Tests.Unit.Business
      - ''
      - dotnet test --logger trx --verbosity=minimal --results-directory /tmp/test
        ./TimeTracker.Tests.Integration.Business
      - ''
      - dotnet test --logger trx --verbosity=minimal --results-directory /tmp/test
        ./TimeTracker.Tests.Integration.Api
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !PullRequestUpdateTrigger
    projects: TimeVic/Main
  jobDependencies:
  - jobName: Build
    requireSuccessful: true
    artifacts: '*/**'
  requiredServices:
  - postgres
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
  postBuildActions:
  - !SendNotificationAction
    condition: always
    receivers: authors
- name: Publish
  jobExecutor: onedev-executor-1
  steps:
  - !CommandStep
    name: Build and push main docker image
    runInContainer: true
    image: docker
    interpreter: !DefaultInterpreter
      commands:
      - 'echo "Environment: @param:environment@"'
      - ''
      - if [ "@param:environment@" = "prod" ]; then
      - "\timage=\"lampego/timevic-main\""
      - else
      - "\timage=\"lampego/timevic-main-dev\""
      - fi
      - ''
      - imageVersion="@build_number@"
      - imageName="$image:$imageVersion"
      - latestImageName="$image:latest"
      - ''
      - docker build --file="devops/onedev/common/Dockerfile" -t $imageName .
      - docker login -u "@secret:dockerhub-login@" -p "@secret:dockerhub-password@"
      - docker push $imageName
      - docker tag $imageName $latestImageName
      - docker push $latestImageName
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build and push web docker image
    runInContainer: true
    image: docker
    interpreter: !DefaultInterpreter
      commands:
      - if [ "@param:environment@" = "prod" ]; then
      - "\timage=\"lampego/timevic-web\""
      - else
      - "\timage=\"lampego/timevic-web-dev\""
      - fi
      - ''
      - imageVersion="@build_number@"
      - imageName="$image:$imageVersion"
      - latestImageName="$image:latest"
      - ''
      - docker build --file="devops/onedev/web/Dockerfile" -t $imageName .
      - docker login -u "@secret:dockerhub-login@" -p "@secret:dockerhub-password@"
      - docker push $imageName
      - docker tag $imageName $latestImageName
      - docker push $latestImageName
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  paramSpecs:
  - !ChoiceParam
    name: environment
    allowMultiple: false
    allowEmpty: false
    choiceProvider: !SpecifiedChoices
      choices:
      - value: dev
        color: '#0d87e9'
      - value: prod
        color: '#0d87e9'
    defaultValueProvider: !SpecifiedDefaultValue
      value: dev
  jobDependencies:
  - jobName: Build
    requireSuccessful: true
    artifacts: '*/** -.git'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Deploy
  jobExecutor: abedor-web-1
  steps:
  - !CommandStep
    name: Stop and remove images
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - 'echo "Environment: @param:environment@"'
      - ''
      - if [ "@param:environment@" = "prod" ]; then
      - "\tdocker rm -f timevic-main-api || true"
      - "\tdocker rm -f timevic-main-worker || true"
      - "\tdocker rm -f timevic-web || true"
      - ''
      - "\tdocker image rm -f lampego/timevic-main || true"
      - "\tdocker image rm -f lampego/timevic-web || true"
      - else
      - "\tdocker rm -f timevic-main-api-dev || true"
      - "\tdocker rm -f timevic-main-worker-dev || true"
      - "\tdocker rm -f timevic-web-dev || true"
      - ''
      - "\tdocker image rm -f lampego/timevic-main-dev || true"
      - "\tdocker image rm -f lampego/timevic-web-dev || true"
      - fi
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run migrations
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - if [ "@param:environment@" = "prod" ]; then
      - "\timageName=\"lampego/timevic-main\""
      - "\tconnectionString=\"ConnectionStrings__DefaultConnection=User ID=@secret:prod-db-login@;Password=@secret:prod-db-password@;Host=192.168.99.8;Port=5433;Database=timevic;Pooling=true;\""
      - else
      - "\timageName=\"lampego/timevic-main-dev\""
      - "\tconnectionString=\"ConnectionStrings__DefaultConnection=User ID=@secret:dev-db-login@;Password=@secret:dev-db-password@;Host=192.168.99.8;Port=5433;Database=timevic_dev;Pooling=true;\""
      - fi
      - ''
      - docker run \
      - -e "PROJECT_DIR=TimeTracker.Migrations" \
      - -e "Serilog__MinimumLevel__Default=Debug" \
      - -e "$connectionString" \
      - '"$imageName" \'
      - \
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run backend containers
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - if [ "@param:environment@" = "prod" ]; then
      - "\timageName=\"lampego/timevic-main\""
      - "\tportApi=\"6200:80\""
      - "\tcontainerNameBgJob=\"timevic-main-worker\""
      - "\tcontainerNameApi=\"timevic-main-api\""
      - "\tconnectionString=\"ConnectionStrings__DefaultConnection=User ID=@secret:prod-db-login@;Password=@secret:prod-db-password@;Host=192.168.99.8;Port=5433;Database=timevic;Pooling=true;\""
      - "\tfrontendUrl=\"https://timevic.com\""
      - "\tauthSymmetricKey=\"@secret:prod-auth-symmetric-security-key@\""
      - "\ts3SecretKey=\"@secret:prod-s3-secret-key@\""
      - "\ts3AccessKey=\"@secret:prod-s3-access-key@\""
      - "\ts3BucketName=\"@secret:prod-s3-bucket-name@\""
      - else
      - "\timageName=\"lampego/timevic-main-dev\""
      - "\tportApi=\"8215:80\""
      - "\tcontainerNameBgJob=\"timevic-main-worker-dev\""
      - "\tcontainerNameApi=\"timevic-main-api-dev\""
      - "\tconnectionString=\"ConnectionStrings__DefaultConnection=User ID=@secret:dev-db-login@;Password=@secret:dev-db-password@;Host=192.168.99.8;Port=5433;Database=timevic_dev;Pooling=true;\""
      - "\tfrontendUrl=\"https://dev.timevic.com\""
      - "\tauthSymmetricKey=\"@secret:dev-auth-symmetric-security-key@\""
      - "\ts3SecretKey=\"@secret:dev-s3-secret-key@\""
      - "\ts3AccessKey=\"@secret:dev-s3-access-key@\""
      - "\ts3BucketName=\"@secret:dev-s3-bucket-name@\""
      - fi
      - ''
      - docker run -d --restart=always --name=$containerNameBgJob \
      - -e "PROJECT_DIR=TimeTracker.WorkerServices" \
      - -e "Serilog__MinimumLevel__Default=Debug" \
      - -e "$connectionString" \
      - -e "App__FrontendUrl=$frontendUrl" \
      - -e "Serilog__IsSendEmailIfError=false" \
      - -e "Redis__Server=10.10.0.2:6379" \
      - -e "Smtp__UserName=@secret:prod-smtp-login@" \
      - -e "Smtp__Password=@secret:prod-smtp-password@" \
      - -e "App__Auth__SymmetricSecurityKey=$authSymmetricKey" \
      - -e "ReCaptcha__Secret=@secret:prod-recaptcha-secret@" \
      - -e "AWS__S3__AccessKey=$s3AccessKey" \
      - -e "AWS__S3__SecretKey=$s3SecretKey" \
      - -e "AWS__S3__BucketName=$s3BucketName" \
      - '"$imageName"'
      - ''
      - docker run -d -p "$portApi" --restart=always --name=$containerNameApi \
      - -e "PROJECT_DIR=TimeTracker.Api" \
      - -e "Serilog__MinimumLevel__Default=Debug" \
      - -e "$connectionString" \
      - -e "App__FrontendUrl=$frontendUrl" \
      - -e "Serilog__IsSendEmailIfError=false" \
      - -e "Redis__Server=10.10.0.2:6379" \
      - -e "Smtp__UserName=@secret:prod-smtp-login@" \
      - -e "Smtp__Password=@secret:prod-smtp-password@" \
      - -e "App__Auth__SymmetricSecurityKey=$authSymmetricKey" \
      - -e "ReCaptcha__Secret=@secret:prod-recaptcha-secret@" \
      - -e "AWS__S3__AccessKey=$s3AccessKey" \
      - -e "AWS__S3__SecretKey=$s3SecretKey" \
      - -e "AWS__S3__BucketName=$s3BucketName" \
      - '"$imageName"'
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run Web container
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - if [ "@param:environment@" = "prod" ]; then
      - "\timageName=\"lampego/timevic-web\""
      - "\tcontainerName=\"timevic-web\""
      - "\tport=\"6201:80\""
      - else
      - "\timageName=\"lampego/timevic-web-dev\""
      - "\tcontainerName=\"timevic-web-dev\""
      - "\tport=\"8216:80\""
      - fi
      - ''
      - docker run -d --restart=always -p $port --name=$containerName \
      - $imageName \
      - \
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  paramSpecs:
  - !ChoiceParam
    name: environment
    allowMultiple: false
    allowEmpty: false
    choiceProvider: !SpecifiedChoices
      choices:
      - value: dev
        color: '#0d87e9'
      - value: prod
        color: '#0d87e9'
  triggers:
  - !PullRequestMergeTrigger
    branches: dev
    projects: TimeVic/Main
    params:
    - name: environment
      valuesProvider: !SpecifiedValues
        values:
        - - dev
      secret: false
  - !PullRequestMergeTrigger
    branches: main
    params:
    - name: environment
      valuesProvider: !SpecifiedValues
        values:
        - - prod
      secret: false
  jobDependencies:
  - jobName: Publish
    requireSuccessful: true
    jobParams:
    - name: environment
      valuesProvider: !PassthroughValues
        paramName: environment
      secret: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
  postBuildActions:
  - !SendNotificationAction
    condition: successful
    receivers: authors
  - !SendNotificationAction
    condition: failed
    receivers: authors
services:
- name: postgres
  image: postgres:15
  envVars:
  - name: POSTGRES_PASSWORD
    value: postgres
  readinessCheckCommand: exec pg_isready -h 127.0.0.1 -p 5432
