<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>CS0168,CS8602,CS0169,CS1998</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain.Abstractions\Domain.Abstractions.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.Common\TimeTracker.Business.Common.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.Extensions\TimeTracker.Business.Extensions.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.Logging\TimeTracker.Business.Logging.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FirebaseAdmin" Version="3.6.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    </ItemGroup>

</Project>
