<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <WarningsAsErrors>CS0168,CS8602,CS0169,CS1998</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" Version="9.1.0" />
      <PackageReference Include="FluentNHibernate" Version="3.4.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.5" />
      <PackageReference Include="NHibernate" Version="5.6.0" />
      <PackageReference Include="NHibernate.Mapping.Attributes" Version="5.1.0" />
      <PackageReference Include="Npgsql" Version="10.0.2" />
      <PackageReference Include="Serilog" Version="4.3.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Persistence.Transactions.Behaviors\Persistence.Transactions.Behaviors.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.Common\TimeTracker.Business.Common.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.Extensions\TimeTracker.Business.Extensions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Dao\FileStorage\" />
      <Folder Include="Queries\Hibernate\" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Queries\Sql\TimeEntry\GetListGroupedByDayIds.sql" />
      <None Remove="Hibernate\hibernate.hbm.xml" />
      <EmbeddedResource Include="Hibernate\hibernate.hbm.xml" />
      <None Remove="Queries\Test\TestNamedQuery.hbm.xml" />
      <None Remove="Queries\TimeEntry\GetListGroupedByDayIds.sql" />
      <None Remove="Queries\Sql\Report\ProjectPayments.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\ProjectPayments.sql" />
      <None Remove="Queries\Sql\Report\SummaryByClientForOther.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\SummaryByClientForOther.sql" />
      <None Remove="Queries\Sql\Report\SummaryByClientForOwner.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\SummaryByClientForOwner.sql" />
      <None Remove="Queries\Sql\Report\SummaryByDayForOthers.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\SummaryByDayForOthers.sql" />
      <None Remove="Queries\Sql\Report\SummaryByDayForOwner.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\SummaryByDayForOwner.sql" />
      <None Remove="Queries\Sql\Report\SummaryByMonthForOther.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\SummaryByMonthForOther.sql" />
      <None Remove="Queries\Sql\Report\SummaryByMonthForOwner.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\SummaryByMonthForOwner.sql" />
      <None Remove="Queries\Sql\Report\SummaryByProjectForOther.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\SummaryByProjectForOther.sql" />
      <None Remove="Queries\Sql\Report\SummaryByProjectForOwner.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\SummaryByProjectForOwner.sql" />
      <None Remove="Queries\Sql\Report\SummaryByUserForOther.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\SummaryByUserForOther.sql" />
      <None Remove="Queries\Sql\Report\SummaryByUserForOwner.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\SummaryByUserForOwner.sql" />
      <None Remove="Queries\Sql\Report\SummaryByWeekForOther.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\SummaryByWeekForOther.sql" />
      <None Remove="Queries\Sql\Report\SummaryByWeekForOwner.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\SummaryByWeekForOwner.sql" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Entities\FileStorage\FileStorageBucketEntity.cs" />
      <Compile Remove="Entities\FileStorage\FileStorageDirectoryEntity.cs" />
      <Compile Remove="Entities\FileStorage\FileStorageFileEntity.cs" />
      <Compile Remove="Dao\FileStorage\FileStorageAccessKeyDao.cs" />
      <Compile Remove="Dao\FileStorage\FileStorageBucketDao.cs" />
      <Compile Remove="Dao\FileStorage\FileStorageDirectoryDao.cs" />
      <Compile Remove="Dao\FileStorage\FileStorageFileDao.cs" />
      <Compile Remove="Dao\FileStorage\IFileStorageAccessKeyDao.cs" />
      <Compile Remove="Dao\FileStorage\IFileStorageBucketDao.cs" />
      <Compile Remove="Dao\FileStorage\IFileStorageDirectoryDao.cs" />
      <Compile Remove="Dao\FileStorage\IFileStorageFileDao.cs" />
    </ItemGroup>

</Project>
