<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <WarningsAsErrors>CS0168,CS8602,CS0169,CS1998</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" Version="9.3.2" />
      <PackageReference Include="FluentNHibernate" Version="3.4.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.10" />
      <PackageReference Include="NHibernate" Version="5.7.0" />
      <PackageReference Include="NHibernate.Mapping.Attributes" Version="5.1.0" />
      <PackageReference Include="Npgsql" Version="10.0.3" />
      <PackageReference Include="Serilog" Version="4.4.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Persistence.Transactions.Behaviors\Persistence.Transactions.Behaviors.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.Common\TimeTracker.Business.Common.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.Extensions\TimeTracker.Business.Extensions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Dao\FileStorage\" />
      <Folder Include="Queries\Hibernate\" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Queries\Sql\TimeEntry\GetListGroupedByDayIds.sql" />
      <None Remove="Hibernate\hibernate.hbm.xml" />
      <EmbeddedResource Include="Hibernate\hibernate.hbm.xml" />
      <None Remove="Queries\Test\TestNamedQuery.hbm.xml" />
      <None Remove="Queries\TimeEntry\GetListGroupedByDayIds.sql" />
      <None Remove="Queries\Sql\Report\ProjectMemberPayments\Payments.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\ProjectMemberPayments\Payments.sql" />
      <None Remove="Queries\Sql\Report\Summary\ByClient.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\Summary\ByClient.sql" />
      <None Remove="Queries\Sql\Report\Summary\ByDay.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\Summary\ByDay.sql" />
      <None Remove="Queries\Sql\Report\Summary\ByMonth.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\Summary\ByMonth.sql" />
      <None Remove="Queries\Sql\Report\Summary\ByProject.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\Summary\ByProject.sql" />
      <None Remove="Queries\Sql\Report\Summary\ByWeek.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\Summary\ByWeek.sql" />
      <None Remove="Queries\Sql\Report\TeamSummary\ByDay.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\TeamSummary\ByDay.sql" />
      <None Remove="Queries\Sql\Report\TeamSummary\ByMember.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\TeamSummary\ByMember.sql" />
      <None Remove="Queries\Sql\Report\WorkspaceFinancialSummary\ClientBalances.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\WorkspaceFinancialSummary\ClientBalances.sql" />
      <None Remove="Queries\Sql\Report\WorkspaceFinancialSummary\ClientProjects.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\WorkspaceFinancialSummary\ClientProjects.sql" />
      <None Remove="Queries\Sql\Report\UserPaymentReport\ProjectEarnings.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\UserPaymentReport\ProjectEarnings.sql" />
      <None Remove="Queries\Sql\Report\UserPaymentReport\ClientPayments.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\UserPaymentReport\ClientPayments.sql" />
      <None Remove="Queries\Sql\Report\ClientFinancialReport\ClientPayments.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\ClientFinancialReport\ClientPayments.sql" />
      <None Remove="Queries\Sql\Report\ClientFinancialReport\Tasks.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\ClientFinancialReport\Tasks.sql" />
      <None Remove="Queries\Sql\Report\ClientFinancialReport\TasksCount.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\ClientFinancialReport\TasksCount.sql" />
      <None Remove="Queries\Sql\Report\WorkspaceFinancialSummary\MemberBalances.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\WorkspaceFinancialSummary\MemberBalances.sql" />
      <None Remove="Queries\Sql\Report\WorkspaceFinancialSummary\MemberProjects.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\WorkspaceFinancialSummary\MemberProjects.sql" />
      <None Remove="Queries\Sql\Report\WorkspaceFinancialSummary\ProjectProfitability.sql" />
      <EmbeddedResource Include="Queries\Sql\Report\WorkspaceFinancialSummary\ProjectProfitability.sql" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Entities\FileStorage\FileStorageBucketEntity.cs" />
      <Compile Remove="Entities\FileStorage\FileStorageDirectoryEntity.cs" />
      <Compile Remove="Entities\FileStorage\FileStorageFileEntity.cs" />
      <Compile Remove="Dao\FileStorage\FileStorageAccessKeyDao.cs" />
      <Compile Remove="Dao\FileStorage\FileStorageBucketDao.cs" />
      <Compile Remove="Dao\FileStorage\FileStorageDirectoryDao.cs" />
      <Compile Remove="Dao\FileStorage\FileStorageFileDao.cs" />
      <Compile Remove="Dao\FileStorage\IFileStorageAccessKeyDao.cs" />
      <Compile Remove="Dao\FileStorage\IFileStorageBucketDao.cs" />
      <Compile Remove="Dao\FileStorage\IFileStorageDirectoryDao.cs" />
      <Compile Remove="Dao\FileStorage\IFileStorageFileDao.cs" />
    </ItemGroup>

</Project>
