//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Business.Extensions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTracker.Business.Extensions.Resources.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} day ago.
        /// </summary>
        internal static string DayAgo {
            get {
                return ResourceManager.GetString("DayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} days ago.
        /// </summary>
        internal static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} days ago.
        /// </summary>
        internal static string DaysAgoV2 {
            get {
                return ResourceManager.GetString("DaysAgoV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} hour ago.
        /// </summary>
        internal static string HourAgo {
            get {
                return ResourceManager.GetString("HourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} hours ago.
        /// </summary>
        internal static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} hours ago.
        /// </summary>
        internal static string HoursAgoV2 {
            get {
                return ResourceManager.GetString("HoursAgoV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  just now.
        /// </summary>
        internal static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} minute ago.
        /// </summary>
        internal static string MinuteAgo {
            get {
                return ResourceManager.GetString("MinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} minutes ago.
        /// </summary>
        internal static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        internal static string MinutesAgoV2 {
            get {
                return ResourceManager.GetString("MinutesAgoV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} month ago.
        /// </summary>
        internal static string MonthAgo {
            get {
                return ResourceManager.GetString("MonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} months ago.
        /// </summary>
        internal static string MonthsAgo {
            get {
                return ResourceManager.GetString("MonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} months ago.
        /// </summary>
        internal static string MonthsAgoV2 {
            get {
                return ResourceManager.GetString("MonthsAgoV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} seconds ago.
        /// </summary>
        internal static string SecondsAgo {
            get {
                return ResourceManager.GetString("SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        internal static string SecondsAgoV2 {
            get {
                return ResourceManager.GetString("SecondsAgoV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} day, .
        /// </summary>
        internal static string TimeSpan_Pattern_Days {
            get {
                return ResourceManager.GetString("TimeSpan_Pattern_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} hour, .
        /// </summary>
        internal static string TimeSpan_Pattern_Hours {
            get {
                return ResourceManager.GetString("TimeSpan_Pattern_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} minute, .
        /// </summary>
        internal static string TimeSpan_Pattern_Minutes {
            get {
                return ResourceManager.GetString("TimeSpan_Pattern_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} days, .
        /// </summary>
        internal static string TimeSpan_Pattern_Plural_Days {
            get {
                return ResourceManager.GetString("TimeSpan_Pattern_Plural_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} hours, .
        /// </summary>
        internal static string TimeSpan_Pattern_Plural_Hours {
            get {
                return ResourceManager.GetString("TimeSpan_Pattern_Plural_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} minutes, .
        /// </summary>
        internal static string TimeSpan_Pattern_Plural_Minutes {
            get {
                return ResourceManager.GetString("TimeSpan_Pattern_Plural_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} seconds, .
        /// </summary>
        internal static string TimeSpan_Pattern_Plural_Seconds {
            get {
                return ResourceManager.GetString("TimeSpan_Pattern_Plural_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} second, .
        /// </summary>
        internal static string TimeSpan_Pattern_Seconds {
            get {
                return ResourceManager.GetString("TimeSpan_Pattern_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 seconds.
        /// </summary>
        internal static string TimeSpan_ZeroSeconds {
            get {
                return ResourceManager.GetString("TimeSpan_ZeroSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} year ago.
        /// </summary>
        internal static string YearAgo {
            get {
                return ResourceManager.GetString("YearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} years ago.
        /// </summary>
        internal static string YearsAgo {
            get {
                return ResourceManager.GetString("YearsAgo", resourceCulture);
            }
        }
    }
}
