using FluentMigrator;
using TimeTracker.Migrations.Code;

namespace TimeTracker.Migrations.Migrations
{
    [Migration(60)]
    public class _60_Alter_Workspace : MyMigration
    {
        public override void Up()
        {
            Create.Table("currencies")
                .WithColumn("id").AsGuid().PrimaryKey().WithDefault(SystemMethods.NewGuid)
                .WithColumn("code").AsString(4).NotNullable().Unique()
                .WithColumn("symbol").AsString(10).NotNullable();
            
            Execute.Sql(@"
                INSERT INTO currencies (code, symbol) VALUES
                ('AED', 'د.إ'),
                ('AFN', '؋'),
                ('ALL', 'L'),
                ('AMD', '֏'),
                ('ANG', 'ƒ'),
                ('AOA', 'Kz'),
                ('ARS', '$'),
                ('AUD', '$'),
                ('AWG', 'ƒ'),
                ('AZN', '₼'),
                ('BAM', 'KM'),
                ('BBD', '$'),
                ('BDT', '৳'),
                ('BGN', 'лв'),
                ('BHD', '.د.ب'),
                ('BIF', 'FBu'),
                ('BMD', '$'),
                ('BND', '$'),
                ('BOB', 'Bs.'),
                ('BRL', 'R$'),
                ('BSD', '$'),
                ('BTN', 'Nu.'),
                ('BWP', 'P'),
                ('BYN', 'Br'),
                ('BZD', 'BZ$'),
                ('CAD', '$'),
                ('CDF', 'FC'),
                ('CHF', 'CHF'),
                ('CLP', '$'),
                ('CNY', '¥'),
                ('COP', '$'),
                ('CRC', '₡'),
                ('CUP', '$'),
                ('CVE', '$'),
                ('CZK', 'Kč'),
                ('DJF', 'Fdj'),
                ('DKK', 'kr'),
                ('DOP', 'RD$'),
                ('DZD', 'د.ج'),
                ('EGP', '£'),
                ('ERN', 'Nfk'),
                ('ETB', 'Br'),
                ('EUR', '€'),
                ('FJD', '$'),
                ('FKP', '£'),
                ('GBP', '£'),
                ('GEL', '₾'),
                ('GHS', '₵'),
                ('GIP', '£'),
                ('GMD', 'D'),
                ('GNF', 'FG'),
                ('GTQ', 'Q'),
                ('GYD', '$'),
                ('HKD', '$'),
                ('HNL', 'L'),
                ('HTG', 'G'),
                ('HUF', 'Ft'),
                ('IDR', 'Rp'),
                ('ILS', '₪'),
                ('INR', '₹'),
                ('IQD', 'ع.د'),
                ('IRR', '﷼'),
                ('ISK', 'kr'),
                ('JMD', 'J$'),
                ('JOD', 'د.ا'),
                ('JPY', '¥'),
                ('KES', 'KSh'),
                ('KGS', 'с'),
                ('KHR', '៛'),
                ('KMF', 'CF'),
                ('KRW', '₩'),
                ('KWD', 'د.ك'),
                ('KYD', '$'),
                ('KZT', '₸'),
                ('LAK', '₭'),
                ('LBP', 'ل.ل'),
                ('LKR', '₨'),
                ('LRD', '$'),
                ('LSL', 'L'),
                ('LYD', 'ل.د'),
                ('MAD', 'د.م.'),
                ('MDL', 'L'),
                ('MGA', 'Ar'),
                ('MKD', 'ден'),
                ('MMK', 'Ks'),
                ('MNT', '₮'),
                ('MOP', 'P'),
                ('MRU', 'UM'),
                ('MUR', '₨'),
                ('MVR', 'Rf'),
                ('MWK', 'MK'),
                ('MXN', '$'),
                ('MYR', 'RM'),
                ('MZN', 'MT'),
                ('NAD', '$'),
                ('NGN', '₦'),
                ('NIO', 'C$'),
                ('NOK', 'kr'),
                ('NPR', '₨'),
                ('NZD', '$'),
                ('OMR', 'ر.ع.'),
                ('PAB', 'B/.'),
                ('PEN', 'S/'),
                ('PGK', 'K'),
                ('PHP', '₱'),
                ('PKR', '₨'),
                ('PLN', 'zł'),
                ('PYG', '₲'),
                ('QAR', 'ر.ق'),
                ('RON', 'lei'),
                ('RSD', 'дин.'),
                ('RUB', '₽'),
                ('RWF', 'FRw'),
                ('SAR', '﷼'),
                ('SBD', '$'),
                ('SCR', '₨'),
                ('SDG', 'ج.س.'),
                ('SEK', 'kr'),
                ('SGD', '$'),
                ('SHP', '£'),
                ('SLE', 'Le'),
                ('SOS', 'Sh'),
                ('SRD', '$'),
                ('SSP', '£'),
                ('STN', 'Db'),
                ('SYP', '£'),
                ('SZL', 'L'),
                ('THB', '฿'),
                ('TJS', 'ЅМ'),
                ('TMT', 'm'),
                ('TND', 'د.ت'),
                ('TOP', 'T$'),
                ('TRY', '₺'),
                ('TTD', 'TT$'),
                ('TWD', 'NT$'),
                ('TZS', 'Sh'),
                ('UAH', '₴'),
                ('UGX', 'USh'),
                ('USD', '$'),
                ('UYU', '$U'),
                ('UZS', 'so''m'),
                ('VES', 'Bs.'),
                ('VND', '₫'),
                ('VUV', 'VT'),
                ('WST', 'WS$'),
                ('XAF', 'FCFA'),
                ('XCD', '$'),
                ('XDR', 'SDR'),
                ('XOF', 'CFA'),
                ('XPF', '₣'),
                ('YER', '﷼'),
                ('ZAR', 'R'),
                ('ZMW', 'ZK'),
                ('ZWL', '$');

            ");
            
            Alter.Table("workspaces")
                .AddColumn("time_zone").AsString().NotNullable().WithDefaultValue("UTC")
                .AddColumn("currency_id").AsGuid().Nullable().ForeignKey("currencies", "id")
                .AddColumn("description").AsString(2048).Nullable();

            Execute.Sql(@"UPDATE workspaces SET currency_id = (SELECT id FROM currencies WHERE code = 'USD')");
            
            Alter.Table("workspaces")
                .AlterColumn("currency_id").AsGuid().NotNullable();
            base.Up();
        }
    }
}
