<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>14</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <WarningsAsErrors>CS0168,CS8602,CS0169,CS1998</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="NHibernate" Version="5.6.1" />
    </ItemGroup>

</Project>
