//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Business.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTracker.Business.Common.Resources.RG", typeof(RG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection &quot;{0}&quot; should contain maximum {1} items.
        /// </summary>
        public static string Error_ArrayIsTooBig {
            get {
                return ResourceManager.GetString("Error_ArrayIsTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; should not be null.
        /// </summary>
        public static string Error_ArrayStringCanNotBeNull {
            get {
                return ResourceManager.GetString("Error_ArrayStringCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; should contain maximum {1} characters.
        /// </summary>
        public static string Error_ArrayStringIsTooLong {
            get {
                return ResourceManager.GetString("Error_ArrayStringIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; should contain minimum {1} characters.
        /// </summary>
        public static string Error_ArrayStringIsTooShort {
            get {
                return ResourceManager.GetString("Error_ArrayStringIsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot;contains incorrect IPv4 address!.
        /// </summary>
        public static string Error_FieldContainsIncorrectIPv4Address {
            get {
                return ResourceManager.GetString("Error_FieldContainsIncorrectIPv4Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; may contain only color HEX.
        /// </summary>
        public static string Error_FieldMayContainOnlyColor {
            get {
                return ResourceManager.GetString("Error_FieldMayContainOnlyColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; may contain only currency code!.
        /// </summary>
        public static string Error_FieldMayContainOnlyCurrencyCode {
            get {
                return ResourceManager.GetString("Error_FieldMayContainOnlyCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; may contain only positive digits!.
        /// </summary>
        public static string Error_FieldMayContainOnlyPositiveDigits {
            get {
                return ResourceManager.GetString("Error_FieldMayContainOnlyPositiveDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; may contain only time zone ID!.
        /// </summary>
        public static string Error_FieldMayContainOnlyTimeZoneId {
            get {
                return ResourceManager.GetString("Error_FieldMayContainOnlyTimeZoneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; contains incorrect Base64 value!.
        /// </summary>
        public static string Error_IncorrectBase64 {
            get {
                return ResourceManager.GetString("Error_IncorrectBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; contains incorrect constant value!.
        /// </summary>
        public static string Error_IncorrectConstantValue {
            get {
                return ResourceManager.GetString("Error_IncorrectConstantValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; contains incorrect date!.
        /// </summary>
        public static string Error_IncorrectDate {
            get {
                return ResourceManager.GetString("Error_IncorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; contains incorrect re-captcha token!.
        /// </summary>
        public static string Error_IncorrectReCaptchaToken {
            get {
                return ResourceManager.GetString("Error_IncorrectReCaptchaToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; contains incorrect time entry&apos;s time!.
        /// </summary>
        public static string Error_IncorrectTimeEntryTime {
            get {
                return ResourceManager.GetString("Error_IncorrectTimeEntryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not have access to do this..
        /// </summary>
        public static string Error_UserHasNotPermissions {
            get {
                return ResourceManager.GetString("Error_UserHasNotPermissions", resourceCulture);
            }
        }
    }
}
