//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Business.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RG {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RG() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TimeTracker.Business.Common.Resources.RG", typeof(RG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Error_IncorrectConstantValue {
            get {
                return ResourceManager.GetString("Error_IncorrectConstantValue", resourceCulture);
            }
        }
        
        public static string Error_IncorrectBase64 {
            get {
                return ResourceManager.GetString("Error_IncorrectBase64", resourceCulture);
            }
        }
        
        public static string Error_FieldMayContainOnlyPositiveDigits {
            get {
                return ResourceManager.GetString("Error_FieldMayContainOnlyPositiveDigits", resourceCulture);
            }
        }
        
        public static string Error_FieldMayContainOnlyTimeZoneId {
            get {
                return ResourceManager.GetString("Error_FieldMayContainOnlyTimeZoneId", resourceCulture);
            }
        }
        
        public static string Error_FieldMayContainOnlySlugSymbols {
            get {
                return ResourceManager.GetString("Error_FieldMayContainOnlySlugSymbols", resourceCulture);
            }
        }
        
        public static string Error_FieldMayContainOnlyColor {
            get {
                return ResourceManager.GetString("Error_FieldMayContainOnlyColor", resourceCulture);
            }
        }
        
        public static string Error_ArrayStringIsTooLong {
            get {
                return ResourceManager.GetString("Error_ArrayStringIsTooLong", resourceCulture);
            }
        }
        
        public static string Error_ArrayIsTooBig {
            get {
                return ResourceManager.GetString("Error_ArrayIsTooBig", resourceCulture);
            }
        }
        
        public static string Error_ArrayStringIsTooShort {
            get {
                return ResourceManager.GetString("Error_ArrayStringIsTooShort", resourceCulture);
            }
        }
        
        public static string Error_ArrayStringCanNotBeNull {
            get {
                return ResourceManager.GetString("Error_ArrayStringCanNotBeNull", resourceCulture);
            }
        }
        
        public static string Error_FieldContainsIncorrectIPv4Address {
            get {
                return ResourceManager.GetString("Error_FieldContainsIncorrectIPv4Address", resourceCulture);
            }
        }
        
        public static string Error_FieldMayContainOnlyCurrencyCode {
            get {
                return ResourceManager.GetString("Error_FieldMayContainOnlyCurrencyCode", resourceCulture);
            }
        }
        
        public static string Error_IncorrectReCaptchaToken {
            get {
                return ResourceManager.GetString("Error_IncorrectReCaptchaToken", resourceCulture);
            }
        }
        
        public static string Error_UserHasNotPermissions {
            get {
                return ResourceManager.GetString("Error_UserHasNotPermissions", resourceCulture);
            }
        }
        
        public static string Error_DataValidationException {
            get {
                return ResourceManager.GetString("Error_DataValidationException", resourceCulture);
            }
        }
        
        public static string Error_IncorrectDate {
            get {
                return ResourceManager.GetString("Error_IncorrectDate", resourceCulture);
            }
        }
        
        public static string Error_IncorrectTimeEntryTime {
            get {
                return ResourceManager.GetString("Error_IncorrectTimeEntryTime", resourceCulture);
            }
        }
        
        public static string Error_ExpiredJwtToken {
            get {
                return ResourceManager.GetString("Error_ExpiredJwtToken", resourceCulture);
            }
        }
    }
}
