using Microsoft.AspNetCore.Components;

namespace TimeTracker.Web.Ui.Shared.Components.Form;

public partial class SelectEmojiButton
{
    public class EmojiOptionModel
    {
        public required string Symbol { get; set; }
        public required string Name { get; set; }
        public required string HtmlCode { get; set; }
        public required string Category { get; set; }
        public required string Keywords { get; set; }
    }
    
    [Parameter]
    public EventCallback<EmojiOptionModel> OnSelected { get; set; }
    
    public bool _isShowPopup { get; set; }
    
    private async Task OnShowSelectEmoji()
    {
        _isShowPopup = true;
        await Task.CompletedTask;
    }
    
    private async Task OnSelectEmoji(EmojiOptionModel emoji)
    {
        _isShowPopup = false;
        await OnSelected.InvokeAsync(emoji);
    }
    
    private static readonly List<EmojiOptionModel> EmojiOptions =
    [
        new() { Symbol = "😀", Name = "Grinning Face", HtmlCode = "&#128512;", Category = "Smileys", Keywords = "happy smile grin face" },
        new() { Symbol = "😃", Name = "Smiling Face With Big Eyes", HtmlCode = "&#128515;", Category = "Smileys", Keywords = "happy joy smile face" },
        new() { Symbol = "😄", Name = "Smiling Face With Smiling Eyes", HtmlCode = "&#128516;", Category = "Smileys", Keywords = "cheerful smile laugh" },
        new() { Symbol = "😁", Name = "Beaming Face With Smiling Eyes", HtmlCode = "&#128513;", Category = "Smileys", Keywords = "grin happy excited" },
        new() { Symbol = "😆", Name = "Grinning Squinting Face", HtmlCode = "&#128518;", Category = "Smileys", Keywords = "laugh lol funny" },
        new() { Symbol = "😅", Name = "Grinning Face With Sweat", HtmlCode = "&#128517;", Category = "Smileys", Keywords = "relief nervous awkward" },
        new() { Symbol = "🤣", Name = "Rolling On The Floor Laughing", HtmlCode = "&#129315;", Category = "Smileys", Keywords = "rofl laugh funny lol" },
        new() { Symbol = "😂", Name = "Face With Tears Of Joy", HtmlCode = "&#128514;", Category = "Smileys", Keywords = "tears joy laugh funny" },
        new() { Symbol = "🙂", Name = "Slightly Smiling Face", HtmlCode = "&#128578;", Category = "Smileys", Keywords = "smile calm friendly" },
        new() { Symbol = "🙃", Name = "Upside-Down Face", HtmlCode = "&#128579;", Category = "Smileys", Keywords = "sarcasm playful upside down" },
        new() { Symbol = "😉", Name = "Winking Face", HtmlCode = "&#128521;", Category = "Smileys", Keywords = "wink playful hint" },
        new() { Symbol = "😊", Name = "Smiling Face With Smiling Eyes", HtmlCode = "&#128522;", Category = "Smileys", Keywords = "blush pleased warm" },
        new() { Symbol = "😇", Name = "Smiling Face With Halo", HtmlCode = "&#128519;", Category = "Smileys", Keywords = "angel halo innocent" },
        new() { Symbol = "🥰", Name = "Smiling Face With Hearts", HtmlCode = "&#129392;", Category = "Smileys", Keywords = "love hearts adore" },
        new() { Symbol = "😍", Name = "Smiling Face With Heart-Eyes", HtmlCode = "&#128525;", Category = "Smileys", Keywords = "love heart eyes crush" },
        new() { Symbol = "🤩", Name = "Star-Struck", HtmlCode = "&#129321;", Category = "Smileys", Keywords = "star wow excited" },
        new() { Symbol = "😘", Name = "Face Blowing A Kiss", HtmlCode = "&#128536;", Category = "Smileys", Keywords = "kiss love thanks" },
        new() { Symbol = "😗", Name = "Kissing Face", HtmlCode = "&#128535;", Category = "Smileys", Keywords = "kiss affection" },
        new() { Symbol = "😋", Name = "Face Savoring Food", HtmlCode = "&#128523;", Category = "Smileys", Keywords = "yum tasty delicious" },
        new() { Symbol = "😎", Name = "Smiling Face With Sunglasses", HtmlCode = "&#128526;", Category = "Smileys", Keywords = "cool sunglasses chill" },
        new() { Symbol = "🤓", Name = "Nerd Face", HtmlCode = "&#129299;", Category = "Smileys", Keywords = "smart geek glasses" },
        new() { Symbol = "🧐", Name = "Face With Monocle", HtmlCode = "&#129488;", Category = "Smileys", Keywords = "fancy inspect curious" },
        new() { Symbol = "🥳", Name = "Partying Face", HtmlCode = "&#129395;", Category = "Smileys", Keywords = "party celebration confetti" },
        new() { Symbol = "😏", Name = "Smirking Face", HtmlCode = "&#128527;", Category = "Smileys", Keywords = "smirk sly confident" },
        new() { Symbol = "😒", Name = "Unamused Face", HtmlCode = "&#128530;", Category = "Smileys", Keywords = "annoyed meh bored" },
        new() { Symbol = "😞", Name = "Disappointed Face", HtmlCode = "&#128542;", Category = "Smileys", Keywords = "sad disappointed upset" },
        new() { Symbol = "😔", Name = "Pensive Face", HtmlCode = "&#128532;", Category = "Smileys", Keywords = "pensive sad thoughtful" },
        new() { Symbol = "😢", Name = "Crying Face", HtmlCode = "&#128546;", Category = "Smileys", Keywords = "cry sad tears" },
        new() { Symbol = "😭", Name = "Loudly Crying Face", HtmlCode = "&#128557;", Category = "Smileys", Keywords = "sob tears intense sad" },
        new() { Symbol = "😤", Name = "Face With Steam From Nose", HtmlCode = "&#128548;", Category = "Smileys", Keywords = "frustrated proud steam" },
        new() { Symbol = "😡", Name = "Pouting Face", HtmlCode = "&#128545;", Category = "Smileys", Keywords = "angry mad rage" },
        new() { Symbol = "🤯", Name = "Exploding Head", HtmlCode = "&#129327;", Category = "Smileys", Keywords = "mind blown shock" },
        new() { Symbol = "😱", Name = "Face Screaming In Fear", HtmlCode = "&#128561;", Category = "Smileys", Keywords = "shock scream fear" },
        new() { Symbol = "🥶", Name = "Cold Face", HtmlCode = "&#129398;", Category = "Smileys", Keywords = "cold freezing winter" },
        new() { Symbol = "🥵", Name = "Hot Face", HtmlCode = "&#129397;", Category = "Smileys", Keywords = "hot warm sweat" },
        new() { Symbol = "😴", Name = "Sleeping Face", HtmlCode = "&#128564;", Category = "Smileys", Keywords = "sleep tired rest" },
        new() { Symbol = "🤗", Name = "Hugging Face", HtmlCode = "&#129303;", Category = "Smileys", Keywords = "hug welcome care" },
        new() { Symbol = "🤔", Name = "Thinking Face", HtmlCode = "&#129300;", Category = "Smileys", Keywords = "think idea hmm" },
        new() { Symbol = "🤭", Name = "Face With Hand Over Mouth", HtmlCode = "&#129325;", Category = "Smileys", Keywords = "oops surprise giggle" },
        new() { Symbol = "🤫", Name = "Shushing Face", HtmlCode = "&#129323;", Category = "Smileys", Keywords = "quiet hush secret" },
        new() { Symbol = "🥹", Name = "Face Holding Back Tears", HtmlCode = "&#129402;", Category = "Smileys", Keywords = "tears touched emotional" },
        new() { Symbol = "😌", Name = "Relieved Face", HtmlCode = "&#128524;", Category = "Smileys", Keywords = "relief calm content" },
        new() { Symbol = "🤠", Name = "Cowboy Hat Face", HtmlCode = "&#129312;", Category = "Smileys", Keywords = "cowboy hat face fun" },
        new() { Symbol = "🥸", Name = "Disguised Face", HtmlCode = "&#129400;", Category = "Smileys", Keywords = "disguise glasses mustache" },
        new() { Symbol = "🤪", Name = "Zany Face", HtmlCode = "&#129322;", Category = "Smileys", Keywords = "crazy silly goofy" },
        new()
        {
            Symbol = "😵‍💫", Name = "Face With Spiral Eyes", HtmlCode = "&#128565;&#8205;&#128171;", Category = "Smileys", Keywords = "dizzy spiral confused"
        },

        new() { Symbol = "❤️", Name = "Red Heart", HtmlCode = "&#10084;&#65039;", Category = "Hearts", Keywords = "heart love red" },
        new() { Symbol = "🩷", Name = "Pink Heart", HtmlCode = "&#129655;", Category = "Hearts", Keywords = "heart pink cute" },
        new() { Symbol = "🩵", Name = "Light Blue Heart", HtmlCode = "&#129653;", Category = "Hearts", Keywords = "heart blue light sky" },
        new() { Symbol = "🩶", Name = "Grey Heart", HtmlCode = "&#129654;", Category = "Hearts", Keywords = "heart gray silver" },
        new() { Symbol = "🧡", Name = "Orange Heart", HtmlCode = "&#129505;", Category = "Hearts", Keywords = "heart orange care" },
        new() { Symbol = "💛", Name = "Yellow Heart", HtmlCode = "&#128155;", Category = "Hearts", Keywords = "heart yellow friendship" },
        new() { Symbol = "💚", Name = "Green Heart", HtmlCode = "&#128154;", Category = "Hearts", Keywords = "heart green nature" },
        new() { Symbol = "💙", Name = "Blue Heart", HtmlCode = "&#128153;", Category = "Hearts", Keywords = "heart blue trust" },
        new() { Symbol = "💜", Name = "Purple Heart", HtmlCode = "&#128156;", Category = "Hearts", Keywords = "heart purple support" },
        new() { Symbol = "🤎", Name = "Brown Heart", HtmlCode = "&#129294;", Category = "Hearts", Keywords = "heart brown earthy" },
        new() { Symbol = "🖤", Name = "Black Heart", HtmlCode = "&#128420;", Category = "Hearts", Keywords = "heart black dark" },
        new() { Symbol = "🤍", Name = "White Heart", HtmlCode = "&#129293;", Category = "Hearts", Keywords = "heart white pure" },
        new() { Symbol = "💔", Name = "Broken Heart", HtmlCode = "&#128148;", Category = "Hearts", Keywords = "heart broken sad" },
        new() { Symbol = "❣️", Name = "Heart Exclamation", HtmlCode = "&#10083;&#65039;", Category = "Hearts", Keywords = "heart exclamation emphasis" },
        new() { Symbol = "💕", Name = "Two Hearts", HtmlCode = "&#128149;", Category = "Hearts", Keywords = "hearts love affection" },
        new() { Symbol = "💞", Name = "Revolving Hearts", HtmlCode = "&#128158;", Category = "Hearts", Keywords = "hearts sparkle love" },
        new() { Symbol = "💓", Name = "Beating Heart", HtmlCode = "&#128147;", Category = "Hearts", Keywords = "heart beating pulse" },
        new() { Symbol = "💗", Name = "Growing Heart", HtmlCode = "&#128151;", Category = "Hearts", Keywords = "heart grow love" },
        new() { Symbol = "💖", Name = "Sparkling Heart", HtmlCode = "&#128150;", Category = "Hearts", Keywords = "heart sparkle shiny" },
        new() { Symbol = "💘", Name = "Heart With Arrow", HtmlCode = "&#128152;", Category = "Hearts", Keywords = "heart cupid arrow" },
        new() { Symbol = "💝", Name = "Heart With Ribbon", HtmlCode = "&#128157;", Category = "Hearts", Keywords = "heart gift ribbon" },
        new() { Symbol = "🫀", Name = "Anatomical Heart", HtmlCode = "&#129728;", Category = "Hearts", Keywords = "heart organ anatomy" },
        new() { Symbol = "🫶", Name = "Heart Hands", HtmlCode = "&#129782;", Category = "Hearts", Keywords = "love hands heart gesture" },

        new() { Symbol = "🔥", Name = "Fire", HtmlCode = "&#128293;", Category = "Symbols", Keywords = "fire hot lit flame" },
        new() { Symbol = "✨", Name = "Sparkles", HtmlCode = "&#10024;", Category = "Symbols", Keywords = "sparkles shine magic" },
        new() { Symbol = "⭐", Name = "Star", HtmlCode = "&#11088;", Category = "Symbols", Keywords = "star favorite bright" },
        new() { Symbol = "🌟", Name = "Glowing Star", HtmlCode = "&#127775;", Category = "Symbols", Keywords = "star glow sparkle" },
        new() { Symbol = "💫", Name = "Dizzy", HtmlCode = "&#128171;", Category = "Symbols", Keywords = "dizzy stars sparkle" },
        new() { Symbol = "⚡", Name = "High Voltage", HtmlCode = "&#9889;", Category = "Symbols", Keywords = "lightning energy power" },
        new() { Symbol = "💥", Name = "Collision", HtmlCode = "&#128165;", Category = "Symbols", Keywords = "boom collision impact" },
        new() { Symbol = "💯", Name = "Hundred Points", HtmlCode = "&#128175;", Category = "Symbols", Keywords = "100 perfect score" },
        new() { Symbol = "✅", Name = "Check Mark Button", HtmlCode = "&#9989;", Category = "Symbols", Keywords = "check done success" },
        new() { Symbol = "✔️", Name = "Check Mark", HtmlCode = "&#10004;&#65039;", Category = "Symbols", Keywords = "check yes verified" },
        new() { Symbol = "☑️", Name = "Check Box With Check", HtmlCode = "&#9745;&#65039;", Category = "Symbols", Keywords = "checkbox complete task" },
        new() { Symbol = "❌", Name = "Cross Mark", HtmlCode = "&#10060;", Category = "Symbols", Keywords = "close no remove" },
        new() { Symbol = "➕", Name = "Plus", HtmlCode = "&#10133;", Category = "Symbols", Keywords = "plus add new" },
        new() { Symbol = "➖", Name = "Minus", HtmlCode = "&#10134;", Category = "Symbols", Keywords = "minus subtract remove" },
        new() { Symbol = "➗", Name = "Divide", HtmlCode = "&#10135;", Category = "Symbols", Keywords = "divide math symbol" },
        new() { Symbol = "✖️", Name = "Multiply", HtmlCode = "&#10006;&#65039;", Category = "Symbols", Keywords = "multiply times math" },
        new() { Symbol = "❗", Name = "Exclamation Mark", HtmlCode = "&#10071;", Category = "Symbols", Keywords = "important alert exclamation" },
        new() { Symbol = "❓", Name = "Question Mark", HtmlCode = "&#10067;", Category = "Symbols", Keywords = "question help info" },
        new() { Symbol = "‼️", Name = "Double Exclamation Mark", HtmlCode = "&#8252;&#65039;", Category = "Symbols", Keywords = "double exclamation alert" },
        new()
        {
            Symbol = "⁉️", Name = "Exclamation Question Mark", HtmlCode = "&#8265;&#65039;", Category = "Symbols", Keywords = "surprised confused punctuation"
        },
        new() { Symbol = "🔁", Name = "Repeat Button", HtmlCode = "&#128257;", Category = "Symbols", Keywords = "repeat refresh loop" },
        new() { Symbol = "🔄", Name = "Counterclockwise Arrows Button", HtmlCode = "&#128260;", Category = "Symbols", Keywords = "refresh sync rotate" },
        new() { Symbol = "🔃", Name = "Clockwise Vertical Arrows", HtmlCode = "&#128259;", Category = "Symbols", Keywords = "shuffle switch swap" },
        new() { Symbol = "🔀", Name = "Shuffle Tracks Button", HtmlCode = "&#128256;", Category = "Symbols", Keywords = "shuffle mix random" },
        new() { Symbol = "🔗", Name = "Link", HtmlCode = "&#128279;", Category = "Symbols", Keywords = "link chain url" },
        new() { Symbol = "📎", Name = "Paperclip", HtmlCode = "&#128206;", Category = "Symbols", Keywords = "paperclip attach office" },
        new() { Symbol = "📌", Name = "Pushpin", HtmlCode = "&#128204;", Category = "Symbols", Keywords = "pin mark attach" },
        new() { Symbol = "📍", Name = "Round Pushpin", HtmlCode = "&#128205;", Category = "Symbols", Keywords = "pin location marker" },

        new() { Symbol = "🚀", Name = "Rocket", HtmlCode = "&#128640;", Category = "Objects", Keywords = "rocket launch ship startup" },
        new() { Symbol = "💡", Name = "Light Bulb", HtmlCode = "&#128161;", Category = "Objects", Keywords = "idea bulb innovation" },
        new() { Symbol = "🧠", Name = "Brain", HtmlCode = "&#129504;", Category = "Objects", Keywords = "brain smart think" },
        new() { Symbol = "🧲", Name = "Magnet", HtmlCode = "&#129522;", Category = "Objects", Keywords = "magnet attract tool" },
        new() { Symbol = "🔋", Name = "Battery", HtmlCode = "&#128267;", Category = "Objects", Keywords = "battery power energy" },
        new() { Symbol = "🔌", Name = "Electric Plug", HtmlCode = "&#128268;", Category = "Objects", Keywords = "plug power cable" },
        new() { Symbol = "🛠️", Name = "Hammer And Wrench", HtmlCode = "&#128736;&#65039;", Category = "Objects", Keywords = "tools build configure" },
        new() { Symbol = "🧰", Name = "Toolbox", HtmlCode = "&#129520;", Category = "Objects", Keywords = "tools toolbox setup" },
        new() { Symbol = "🧱", Name = "Brick", HtmlCode = "&#129521;", Category = "Objects", Keywords = "brick build construction" },
        new() { Symbol = "⚙️", Name = "Gear", HtmlCode = "&#9881;&#65039;", Category = "Objects", Keywords = "settings gear system" },
        new() { Symbol = "🖥️", Name = "Desktop Computer", HtmlCode = "&#128421;&#65039;", Category = "Objects", Keywords = "desktop computer workstation" },
        new() { Symbol = "💻", Name = "Laptop", HtmlCode = "&#128187;", Category = "Objects", Keywords = "laptop computer work" },
        new() { Symbol = "⌨️", Name = "Keyboard", HtmlCode = "&#9000;&#65039;", Category = "Objects", Keywords = "keyboard type input" },
        new() { Symbol = "🖱️", Name = "Computer Mouse", HtmlCode = "&#128433;&#65039;", Category = "Objects", Keywords = "mouse click device" },
        new() { Symbol = "🖨️", Name = "Printer", HtmlCode = "&#128438;&#65039;", Category = "Objects", Keywords = "printer print office" },
        new() { Symbol = "📱", Name = "Mobile Phone", HtmlCode = "&#128241;", Category = "Objects", Keywords = "phone mobile app" },
        new() { Symbol = "☎️", Name = "Telephone", HtmlCode = "&#9742;&#65039;", Category = "Objects", Keywords = "phone call contact" },
        new() { Symbol = "📞", Name = "Telephone Receiver", HtmlCode = "&#128222;", Category = "Objects", Keywords = "call receive support" },
        new() { Symbol = "📢", Name = "Loudspeaker", HtmlCode = "&#128227;", Category = "Objects", Keywords = "loudspeaker announce megaphone" },
        new() { Symbol = "📣", Name = "Megaphone", HtmlCode = "&#128226;", Category = "Objects", Keywords = "megaphone broadcast announce" },
        new() { Symbol = "🔔", Name = "Bell", HtmlCode = "&#128276;", Category = "Objects", Keywords = "bell notify alert" },
        new() { Symbol = "🔒", Name = "Locked", HtmlCode = "&#128274;", Category = "Objects", Keywords = "lock secure private" },
        new() { Symbol = "🔓", Name = "Unlocked", HtmlCode = "&#128275;", Category = "Objects", Keywords = "unlock open access" },
        new() { Symbol = "🔑", Name = "Key", HtmlCode = "&#128273;", Category = "Objects", Keywords = "key access secret" },
        new() { Symbol = "🗝️", Name = "Old Key", HtmlCode = "&#128477;&#65039;", Category = "Objects", Keywords = "old key vintage secure" },
        new() { Symbol = "🧷", Name = "Safety Pin", HtmlCode = "&#129528;", Category = "Objects", Keywords = "pin secure attach" },
        new() { Symbol = "📝", Name = "Memo", HtmlCode = "&#128221;", Category = "Objects", Keywords = "memo note write" },
        new() { Symbol = "📓", Name = "Notebook", HtmlCode = "&#128211;", Category = "Objects", Keywords = "notebook notes journal" },
        new() { Symbol = "📘", Name = "Blue Book", HtmlCode = "&#128216;", Category = "Objects", Keywords = "book docs knowledge" },
        new() { Symbol = "📙", Name = "Orange Book", HtmlCode = "&#128217;", Category = "Objects", Keywords = "book orange docs" },
        new() { Symbol = "📗", Name = "Green Book", HtmlCode = "&#128215;", Category = "Objects", Keywords = "book green docs" },
        new() { Symbol = "📕", Name = "Closed Book", HtmlCode = "&#128213;", Category = "Objects", Keywords = "book read archive" },
        new()
        {
            Symbol = "🗂️", Name = "Card Index Dividers", HtmlCode = "&#128450;&#65039;", Category = "Objects", Keywords = "folders dividers organization"
        },
        new() { Symbol = "🗃️", Name = "Card File Box", HtmlCode = "&#128451;&#65039;", Category = "Objects", Keywords = "file box archive" },
        new() { Symbol = "📦", Name = "Package", HtmlCode = "&#128230;", Category = "Objects", Keywords = "package box delivery" },
        new() { Symbol = "🪄", Name = "Magic Wand", HtmlCode = "&#129668;", Category = "Objects", Keywords = "magic wand automate" },
        new() { Symbol = "🎁", Name = "Wrapped Gift", HtmlCode = "&#127873;", Category = "Objects", Keywords = "gift present reward" },
        new() { Symbol = "💎", Name = "Gem Stone", HtmlCode = "&#128142;", Category = "Objects", Keywords = "gem premium diamond" },

        new() { Symbol = "🌍", Name = "Globe Showing Europe-Africa", HtmlCode = "&#127757;", Category = "Nature", Keywords = "globe world earth europe" },
        new() { Symbol = "🌎", Name = "Globe Showing Americas", HtmlCode = "&#127758;", Category = "Nature", Keywords = "globe earth americas" },
        new() { Symbol = "🌏", Name = "Globe Showing Asia-Australia", HtmlCode = "&#127759;", Category = "Nature", Keywords = "globe earth asia" },
        new() { Symbol = "🌱", Name = "Seedling", HtmlCode = "&#127793;", Category = "Nature", Keywords = "seedling growth green" },
        new() { Symbol = "🌿", Name = "Herb", HtmlCode = "&#127807;", Category = "Nature", Keywords = "leaf herb fresh" },
        new() { Symbol = "🍃", Name = "Leaf Fluttering In Wind", HtmlCode = "&#127811;", Category = "Nature", Keywords = "leaf wind nature" },
        new() { Symbol = "☘️", Name = "Shamrock", HtmlCode = "&#9752;&#65039;", Category = "Nature", Keywords = "luck green shamrock" },
        new() { Symbol = "🍀", Name = "Four Leaf Clover", HtmlCode = "&#127808;", Category = "Nature", Keywords = "luck clover success" },
        new() { Symbol = "🌵", Name = "Cactus", HtmlCode = "&#127797;", Category = "Nature", Keywords = "cactus desert resilient" },
        new() { Symbol = "🌴", Name = "Palm Tree", HtmlCode = "&#127796;", Category = "Nature", Keywords = "palm tropical vacation" },
        new() { Symbol = "🌲", Name = "Evergreen Tree", HtmlCode = "&#127794;", Category = "Nature", Keywords = "tree forest pine" },
        new() { Symbol = "🌳", Name = "Deciduous Tree", HtmlCode = "&#127795;", Category = "Nature", Keywords = "tree green park" },
        new() { Symbol = "🌸", Name = "Cherry Blossom", HtmlCode = "&#127800;", Category = "Nature", Keywords = "flower blossom spring" },
        new() { Symbol = "🌼", Name = "Blossom", HtmlCode = "&#127804;", Category = "Nature", Keywords = "flower yellow blossom" },
        new() { Symbol = "🌻", Name = "Sunflower", HtmlCode = "&#127803;", Category = "Nature", Keywords = "sunflower flower bright" },
        new() { Symbol = "🌺", Name = "Hibiscus", HtmlCode = "&#127802;", Category = "Nature", Keywords = "hibiscus flower tropical" },
        new() { Symbol = "🌷", Name = "Tulip", HtmlCode = "&#127799;", Category = "Nature", Keywords = "tulip flower spring" },
        new() { Symbol = "🌙", Name = "Crescent Moon", HtmlCode = "&#127769;", Category = "Nature", Keywords = "moon night crescent" },
        new() { Symbol = "🌕", Name = "Full Moon", HtmlCode = "&#127765;", Category = "Nature", Keywords = "moon full night" },
        new() { Symbol = "☀️", Name = "Sun", HtmlCode = "&#9728;&#65039;", Category = "Nature", Keywords = "sun weather bright" },
        new() { Symbol = "🌤️", Name = "Sun Behind Small Cloud", HtmlCode = "&#127780;&#65039;", Category = "Nature", Keywords = "sun cloud partly sunny" },
        new() { Symbol = "🌈", Name = "Rainbow", HtmlCode = "&#127752;", Category = "Nature", Keywords = "rainbow color weather" },
        new() { Symbol = "☁️", Name = "Cloud", HtmlCode = "&#9729;&#65039;", Category = "Nature", Keywords = "cloud weather sky" },
        new() { Symbol = "🌧️", Name = "Cloud With Rain", HtmlCode = "&#127783;&#65039;", Category = "Nature", Keywords = "rain cloud weather" },
        new() { Symbol = "⛈️", Name = "Cloud With Lightning And Rain", HtmlCode = "&#9928;&#65039;", Category = "Nature", Keywords = "storm rain lightning" },
        new() { Symbol = "❄️", Name = "Snowflake", HtmlCode = "&#10052;&#65039;", Category = "Nature", Keywords = "snow winter cold" },
        new() { Symbol = "🌊", Name = "Water Wave", HtmlCode = "&#127754;", Category = "Nature", Keywords = "water wave ocean" },

        new() { Symbol = "🎉", Name = "Party Popper", HtmlCode = "&#127881;", Category = "Celebration", Keywords = "party celebration confetti" },
        new() { Symbol = "🎊", Name = "Confetti Ball", HtmlCode = "&#127882;", Category = "Celebration", Keywords = "confetti party fun" },
        new() { Symbol = "🎈", Name = "Balloon", HtmlCode = "&#127880;", Category = "Celebration", Keywords = "balloon celebration event" },
        new() { Symbol = "🎂", Name = "Birthday Cake", HtmlCode = "&#127874;", Category = "Celebration", Keywords = "cake birthday celebrate" },
        new() { Symbol = "🧁", Name = "Cupcake", HtmlCode = "&#129473;", Category = "Celebration", Keywords = "cupcake dessert sweet party" },
        new() { Symbol = "🍾", Name = "Bottle With Popping Cork", HtmlCode = "&#127870;", Category = "Celebration", Keywords = "bottle party toast" },
        new() { Symbol = "🥂", Name = "Clinking Glasses", HtmlCode = "&#129346;", Category = "Celebration", Keywords = "cheers toast party" },
        new() { Symbol = "🍰", Name = "Shortcake", HtmlCode = "&#127856;", Category = "Celebration", Keywords = "cake dessert celebration" },
        new() { Symbol = "🪅", Name = "Piñata", HtmlCode = "&#129669;", Category = "Celebration", Keywords = "pinata fiesta party" },
        new() { Symbol = "🪩", Name = "Mirror Ball", HtmlCode = "&#129729;", Category = "Celebration", Keywords = "disco mirror ball party" },
        new() { Symbol = "🎆", Name = "Fireworks", HtmlCode = "&#127878;", Category = "Celebration", Keywords = "fireworks holiday celebration" },
        new() { Symbol = "🎇", Name = "Sparkler", HtmlCode = "&#127879;", Category = "Celebration", Keywords = "sparkler fireworks party" },
        new() { Symbol = "🙌", Name = "Raising Hands", HtmlCode = "&#128588;", Category = "Celebration", Keywords = "hooray celebrate hands" },
        new() { Symbol = "👏", Name = "Clapping Hands", HtmlCode = "&#128079;", Category = "Celebration", Keywords = "clap applause bravo" },

        new() { Symbol = "👋", Name = "Waving Hand", HtmlCode = "&#128075;", Category = "People", Keywords = "wave hello goodbye hand" },
        new() { Symbol = "🤚", Name = "Raised Back Of Hand", HtmlCode = "&#129306;", Category = "People", Keywords = "raised hand stop backhand" },
        new()
        {
            Symbol = "🖐️", Name = "Hand With Fingers Splayed", HtmlCode = "&#128400;&#65039;", Category = "People", Keywords = "hand fingers splayed five"
        },
        new() { Symbol = "✋", Name = "Raised Hand", HtmlCode = "&#9995;", Category = "People", Keywords = "raised hand high five stop" },
        new() { Symbol = "🫱", Name = "Rightwards Hand", HtmlCode = "&#129777;", Category = "People", Keywords = "rightwards hand reach gesture" },
        new() { Symbol = "🫲", Name = "Leftwards Hand", HtmlCode = "&#129778;", Category = "People", Keywords = "leftwards hand reach gesture" },
        new() { Symbol = "🫳", Name = "Palm Down Hand", HtmlCode = "&#129779;", Category = "People", Keywords = "palm down hand drop lower" },
        new() { Symbol = "🫴", Name = "Palm Up Hand", HtmlCode = "&#129780;", Category = "People", Keywords = "palm up hand offer receive" },
        new() { Symbol = "👌", Name = "OK Hand", HtmlCode = "&#128076;", Category = "People", Keywords = "ok hand perfect approve" },
        new() { Symbol = "🤌", Name = "Pinched Fingers", HtmlCode = "&#129292;", Category = "People", Keywords = "pinched fingers italian gesture" },
        new() { Symbol = "🤏", Name = "Pinching Hand", HtmlCode = "&#129295;", Category = "People", Keywords = "pinching hand small tiny" },
        new() { Symbol = "✌️", Name = "Victory Hand", HtmlCode = "&#9996;&#65039;", Category = "People", Keywords = "peace victory hand" },
        new() { Symbol = "🤞", Name = "Crossed Fingers", HtmlCode = "&#129310;", Category = "People", Keywords = "crossed fingers luck hope" },
        new()
        {
            Symbol = "🫰", Name = "Hand With Index Finger And Thumb Crossed", HtmlCode = "&#129776;", Category = "People",
            Keywords = "finger heart hand love korean"
        },
        new() { Symbol = "🤟", Name = "Love-You Gesture", HtmlCode = "&#129311;", Category = "People", Keywords = "love you hand sign gesture" },
        new() { Symbol = "🤘", Name = "Sign Of The Horns", HtmlCode = "&#129304;", Category = "People", Keywords = "rock hand horns sign" },
        new() { Symbol = "🤙", Name = "Call Me Hand", HtmlCode = "&#129305;", Category = "People", Keywords = "call me hand phone shaka" },
        new() { Symbol = "👈", Name = "Backhand Index Pointing Left", HtmlCode = "&#128072;", Category = "People", Keywords = "point left finger hand" },
        new() { Symbol = "👉", Name = "Backhand Index Pointing Right", HtmlCode = "&#128073;", Category = "People", Keywords = "point right finger hand" },
        new() { Symbol = "👆", Name = "Backhand Index Pointing Up", HtmlCode = "&#128070;", Category = "People", Keywords = "point up finger hand" },
        new() { Symbol = "🖕", Name = "Middle Finger", HtmlCode = "&#128405;", Category = "People", Keywords = "middle finger rude gesture hand" },
        new() { Symbol = "👇", Name = "Backhand Index Pointing Down", HtmlCode = "&#128071;", Category = "People", Keywords = "point down finger hand" },
        new() { Symbol = "☝️", Name = "Index Pointing Up", HtmlCode = "&#9757;&#65039;", Category = "People", Keywords = "index up point finger" },
        new() { Symbol = "👍", Name = "Thumbs Up", HtmlCode = "&#128077;", Category = "People", Keywords = "thumbsup like approve" },
        new() { Symbol = "👎", Name = "Thumbs Down", HtmlCode = "&#128078;", Category = "People", Keywords = "thumbsdown dislike reject" },
        new() { Symbol = "👊", Name = "Oncoming Fist", HtmlCode = "&#128074;", Category = "People", Keywords = "fist bump power" },
        new() { Symbol = "✊", Name = "Raised Fist", HtmlCode = "&#9994;", Category = "People", Keywords = "raised fist power protest" },
        new() { Symbol = "🤛", Name = "Left-Facing Fist", HtmlCode = "&#129307;", Category = "People", Keywords = "left fist bump punch" },
        new() { Symbol = "🤜", Name = "Right-Facing Fist", HtmlCode = "&#129308;", Category = "People", Keywords = "right fist bump punch" },
        new() { Symbol = "🤝", Name = "Handshake", HtmlCode = "&#129309;", Category = "People", Keywords = "handshake deal agree" },
        new() { Symbol = "🙏", Name = "Folded Hands", HtmlCode = "&#128591;", Category = "People", Keywords = "thanks pray respect" },
        new() { Symbol = "👐", Name = "Open Hands", HtmlCode = "&#128080;", Category = "People", Keywords = "open hands hug welcome" },
        new() { Symbol = "🤲", Name = "Palms Up Together", HtmlCode = "&#129330;", Category = "People", Keywords = "palms up together offer prayer" },
        new() { Symbol = "✍️", Name = "Writing Hand", HtmlCode = "&#9997;&#65039;", Category = "People", Keywords = "writing hand note sign" },
        new() { Symbol = "💪", Name = "Flexed Biceps", HtmlCode = "&#128170;", Category = "People", Keywords = "strong muscle power" },
        new() { Symbol = "👀", Name = "Eyes", HtmlCode = "&#128064;", Category = "People", Keywords = "eyes look watch" },
        new() { Symbol = "👂", Name = "Ear", HtmlCode = "&#128066;", Category = "People", Keywords = "ear listen hear" },
        new() { Symbol = "🫵", Name = "Index Pointing At The Viewer", HtmlCode = "&#129781;", Category = "People", Keywords = "you point viewer hand" },
        new()
        {
            Symbol = "🧑‍💻", Name = "Technologist", HtmlCode = "&#129489;&#8205;&#128187;", Category = "People",
            Keywords = "developer coder laptop technologist"
        },
        new() { Symbol = "🧑‍🎨", Name = "Artist", HtmlCode = "&#129489;&#8205;&#127912;", Category = "People", Keywords = "artist paint creative" },
        new() { Symbol = "🧑‍🚀", Name = "Astronaut", HtmlCode = "&#129489;&#8205;&#128640;", Category = "People", Keywords = "astronaut space rocket" },
        new() { Symbol = "🧑‍💼", Name = "Office Worker", HtmlCode = "&#129489;&#8205;&#128188;", Category = "People", Keywords = "office business worker" },
        new() { Symbol = "🧑‍🏫", Name = "Teacher", HtmlCode = "&#129489;&#8205;&#127979;", Category = "People", Keywords = "teacher school mentor" },

        new() { Symbol = "🐶", Name = "Dog Face", HtmlCode = "&#128054;", Category = "Animals", Keywords = "dog pet puppy" },
        new() { Symbol = "🐱", Name = "Cat Face", HtmlCode = "&#128049;", Category = "Animals", Keywords = "cat pet kitty" },
        new() { Symbol = "🐭", Name = "Mouse Face", HtmlCode = "&#128045;", Category = "Animals", Keywords = "mouse animal cute" },
        new() { Symbol = "🐹", Name = "Hamster", HtmlCode = "&#128057;", Category = "Animals", Keywords = "hamster pet cute" },
        new() { Symbol = "🐰", Name = "Rabbit Face", HtmlCode = "&#128048;", Category = "Animals", Keywords = "rabbit bunny pet" },
        new() { Symbol = "🦊", Name = "Fox", HtmlCode = "&#129418;", Category = "Animals", Keywords = "fox clever animal" },
        new() { Symbol = "🐻", Name = "Bear", HtmlCode = "&#128059;", Category = "Animals", Keywords = "bear animal wild" },
        new() { Symbol = "🐼", Name = "Panda", HtmlCode = "&#128060;", Category = "Animals", Keywords = "panda animal cute" },
        new() { Symbol = "🦁", Name = "Lion", HtmlCode = "&#129409;", Category = "Animals", Keywords = "lion brave animal" },
        new() { Symbol = "🐨", Name = "Koala", HtmlCode = "&#128040;", Category = "Animals", Keywords = "koala animal australia" },
        new() { Symbol = "🐯", Name = "Tiger Face", HtmlCode = "&#128047;", Category = "Animals", Keywords = "tiger wild animal" },
        new() { Symbol = "🐸", Name = "Frog", HtmlCode = "&#128056;", Category = "Animals", Keywords = "frog animal green" },
        new() { Symbol = "🐝", Name = "Honeybee", HtmlCode = "&#128029;", Category = "Animals", Keywords = "bee honey work" },
        new() { Symbol = "🦋", Name = "Butterfly", HtmlCode = "&#129419;", Category = "Animals", Keywords = "butterfly transform nature" },
        new() { Symbol = "🐙", Name = "Octopus", HtmlCode = "&#128025;", Category = "Animals", Keywords = "octopus sea animal" },
        new() { Symbol = "🐬", Name = "Dolphin", HtmlCode = "&#128044;", Category = "Animals", Keywords = "dolphin sea smart" },
        new() { Symbol = "🐳", Name = "Spouting Whale", HtmlCode = "&#128051;", Category = "Animals", Keywords = "whale ocean sea" },
        new() { Symbol = "🦄", Name = "Unicorn", HtmlCode = "&#129412;", Category = "Animals", Keywords = "unicorn magic fantasy" },
        new() { Symbol = "🦉", Name = "Owl", HtmlCode = "&#129417;", Category = "Animals", Keywords = "owl bird wise" },
        new() { Symbol = "🐢", Name = "Turtle", HtmlCode = "&#128034;", Category = "Animals", Keywords = "turtle slow animal" },

        new() { Symbol = "🍎", Name = "Red Apple", HtmlCode = "&#127822;", Category = "Food", Keywords = "apple fruit red" },
        new() { Symbol = "🍊", Name = "Tangerine", HtmlCode = "&#127818;", Category = "Food", Keywords = "orange fruit citrus" },
        new() { Symbol = "🍋", Name = "Lemon", HtmlCode = "&#127819;", Category = "Food", Keywords = "lemon fruit sour" },
        new() { Symbol = "🍉", Name = "Watermelon", HtmlCode = "&#127817;", Category = "Food", Keywords = "watermelon fruit summer" },
        new() { Symbol = "🍇", Name = "Grapes", HtmlCode = "&#127815;", Category = "Food", Keywords = "grapes fruit purple" },
        new() { Symbol = "🍓", Name = "Strawberry", HtmlCode = "&#127827;", Category = "Food", Keywords = "strawberry berry fruit" },
        new() { Symbol = "🫐", Name = "Blueberries", HtmlCode = "&#129744;", Category = "Food", Keywords = "blueberries berry fruit" },
        new() { Symbol = "🍒", Name = "Cherries", HtmlCode = "&#127826;", Category = "Food", Keywords = "cherries fruit sweet" },
        new() { Symbol = "🥑", Name = "Avocado", HtmlCode = "&#129361;", Category = "Food", Keywords = "avocado healthy fruit" },
        new() { Symbol = "🥗", Name = "Green Salad", HtmlCode = "&#129367;", Category = "Food", Keywords = "salad healthy vegetables" },
        new() { Symbol = "🍕", Name = "Pizza", HtmlCode = "&#127829;", Category = "Food", Keywords = "pizza food slice" },
        new() { Symbol = "🍔", Name = "Hamburger", HtmlCode = "&#127828;", Category = "Food", Keywords = "burger fast food" },
        new() { Symbol = "🌮", Name = "Taco", HtmlCode = "&#127790;", Category = "Food", Keywords = "taco mexican food" },
        new() { Symbol = "🍣", Name = "Sushi", HtmlCode = "&#127843;", Category = "Food", Keywords = "sushi japanese food" },
        new() { Symbol = "🍜", Name = "Steaming Bowl", HtmlCode = "&#127836;", Category = "Food", Keywords = "ramen noodles soup" },
        new() { Symbol = "🍩", Name = "Doughnut", HtmlCode = "&#127849;", Category = "Food", Keywords = "donut dessert sweet" },
        new() { Symbol = "🍪", Name = "Cookie", HtmlCode = "&#127850;", Category = "Food", Keywords = "cookie biscuit dessert" },
        new() { Symbol = "🍫", Name = "Chocolate Bar", HtmlCode = "&#127851;", Category = "Food", Keywords = "chocolate sweet dessert" },
        new() { Symbol = "☕", Name = "Hot Beverage", HtmlCode = "&#9749;", Category = "Food", Keywords = "coffee tea hot drink" },
        new() { Symbol = "🍵", Name = "Teacup Without Handle", HtmlCode = "&#127861;", Category = "Food", Keywords = "tea matcha drink" },
        new() { Symbol = "🧋", Name = "Bubble Tea", HtmlCode = "&#129499;", Category = "Food", Keywords = "bubble tea boba drink" },
        new() { Symbol = "🥤", Name = "Cup With Straw", HtmlCode = "&#129380;", Category = "Food", Keywords = "soft drink soda straw" },
        new() { Symbol = "🍺", Name = "Beer Mug", HtmlCode = "&#127866;", Category = "Food", Keywords = "beer drink mug" },
        new() { Symbol = "🍷", Name = "Wine Glass", HtmlCode = "&#127863;", Category = "Food", Keywords = "wine drink glass" },
        new() { Symbol = "🍿", Name = "Popcorn", HtmlCode = "&#127871;", Category = "Food", Keywords = "popcorn snack movie" },

        new() { Symbol = "🏁", Name = "Chequered Flag", HtmlCode = "&#127937;", Category = "Travel", Keywords = "flag finish race" },
        new() { Symbol = "🚗", Name = "Automobile", HtmlCode = "&#128663;", Category = "Travel", Keywords = "car travel drive" },
        new() { Symbol = "🚕", Name = "Taxi", HtmlCode = "&#128661;", Category = "Travel", Keywords = "taxi cab travel" },
        new() { Symbol = "🚙", Name = "Sport Utility Vehicle", HtmlCode = "&#128665;", Category = "Travel", Keywords = "suv car drive" },
        new() { Symbol = "🚌", Name = "Bus", HtmlCode = "&#128652;", Category = "Travel", Keywords = "bus transport commute" },
        new() { Symbol = "🚆", Name = "Train", HtmlCode = "&#128646;", Category = "Travel", Keywords = "train rail commute" },
        new() { Symbol = "🚇", Name = "Metro", HtmlCode = "&#128647;", Category = "Travel", Keywords = "metro subway rail" },
        new() { Symbol = "🚲", Name = "Bicycle", HtmlCode = "&#128690;", Category = "Travel", Keywords = "bike cycle travel" },
        new() { Symbol = "🛴", Name = "Kick Scooter", HtmlCode = "&#128756;", Category = "Travel", Keywords = "scooter ride city" },
        new() { Symbol = "🏍️", Name = "Motorcycle", HtmlCode = "&#127949;&#65039;", Category = "Travel", Keywords = "motorcycle bike speed" },
        new() { Symbol = "✈️", Name = "Airplane", HtmlCode = "&#9992;&#65039;", Category = "Travel", Keywords = "plane fly travel" },
        new() { Symbol = "🛫", Name = "Airplane Departure", HtmlCode = "&#128707;", Category = "Travel", Keywords = "plane departure flight" },
        new() { Symbol = "🛬", Name = "Airplane Arrival", HtmlCode = "&#128708;", Category = "Travel", Keywords = "plane arrival landing" },
        new() { Symbol = "🚁", Name = "Helicopter", HtmlCode = "&#128641;", Category = "Travel", Keywords = "helicopter fly travel" },
        new() { Symbol = "🚢", Name = "Ship", HtmlCode = "&#128674;", Category = "Travel", Keywords = "ship boat travel" },
        new() { Symbol = "⛵", Name = "Sailboat", HtmlCode = "&#9973;", Category = "Travel", Keywords = "sailboat sea travel" },
        new() { Symbol = "🏖️", Name = "Beach With Umbrella", HtmlCode = "&#127958;&#65039;", Category = "Travel", Keywords = "beach vacation relax" },
        new() { Symbol = "🏔️", Name = "Snow-Capped Mountain", HtmlCode = "&#127956;&#65039;", Category = "Travel", Keywords = "mountain travel adventure" },
        new() { Symbol = "🗽", Name = "Statue Of Liberty", HtmlCode = "&#128509;", Category = "Travel", Keywords = "landmark statue liberty" },
        new() { Symbol = "🗼", Name = "Tokyo Tower", HtmlCode = "&#128508;", Category = "Travel", Keywords = "tower landmark japan" },
        new() { Symbol = "🏙️", Name = "Cityscape", HtmlCode = "&#127961;&#65039;", Category = "Travel", Keywords = "city skyline urban" },
        new() { Symbol = "🌆", Name = "Cityscape At Dusk", HtmlCode = "&#127750;", Category = "Travel", Keywords = "city dusk sunset" },
        new() { Symbol = "🌃", Name = "Night With Stars", HtmlCode = "&#127747;", Category = "Travel", Keywords = "night city stars" },

        new() { Symbol = "🎮", Name = "Video Game", HtmlCode = "&#127918;", Category = "Activities", Keywords = "game controller play" },
        new() { Symbol = "🕹️", Name = "Joystick", HtmlCode = "&#128377;&#65039;", Category = "Activities", Keywords = "joystick arcade game" },
        new() { Symbol = "🎰", Name = "Slot Machine", HtmlCode = "&#127920;", Category = "Activities", Keywords = "slot machine casino game" },
        new() { Symbol = "🎲", Name = "Game Die", HtmlCode = "&#127922;", Category = "Activities", Keywords = "dice board game roll" },
        new() { Symbol = "♠️", Name = "Spade Suit", HtmlCode = "&#9824;&#65039;", Category = "Activities", Keywords = "cards spade suit game" },
        new() { Symbol = "♥️", Name = "Heart Suit", HtmlCode = "&#9829;&#65039;", Category = "Activities", Keywords = "cards heart suit game" },
        new() { Symbol = "♦️", Name = "Diamond Suit", HtmlCode = "&#9830;&#65039;", Category = "Activities", Keywords = "cards diamond suit game" },
        new() { Symbol = "♣️", Name = "Club Suit", HtmlCode = "&#9827;&#65039;", Category = "Activities", Keywords = "cards club suit game" },
        new() { Symbol = "🃏", Name = "Joker", HtmlCode = "&#127183;", Category = "Activities", Keywords = "joker cards game wild" },
        new() { Symbol = "🀄", Name = "Mahjong Red Dragon", HtmlCode = "&#126980;", Category = "Activities", Keywords = "mahjong tile game red dragon" },
        new() { Symbol = "🎴", Name = "Flower Playing Cards", HtmlCode = "&#127924;", Category = "Activities", Keywords = "cards hanafuda flower game" },
        new() { Symbol = "🎯", Name = "Direct Hit", HtmlCode = "&#127919;", Category = "Activities", Keywords = "target goal darts" },
        new() { Symbol = "🎳", Name = "Bowling", HtmlCode = "&#127923;", Category = "Activities", Keywords = "bowling pins sport" },
        new() { Symbol = "🎱", Name = "Pool 8 Ball", HtmlCode = "&#127921;", Category = "Activities", Keywords = "billiards pool game" },
        new() { Symbol = "🧩", Name = "Puzzle Piece", HtmlCode = "&#129513;", Category = "Activities", Keywords = "puzzle solve piece" },
        new() { Symbol = "♟️", Name = "Chess Pawn", HtmlCode = "&#9823;&#65039;", Category = "Activities", Keywords = "chess strategy pawn" },
        new() { Symbol = "🎨", Name = "Artist Palette", HtmlCode = "&#127912;", Category = "Activities", Keywords = "art palette create" },
        new() { Symbol = "🎭", Name = "Performing Arts", HtmlCode = "&#127917;", Category = "Activities", Keywords = "theater drama masks stage" },
        new() { Symbol = "🎪", Name = "Circus Tent", HtmlCode = "&#127914;", Category = "Activities", Keywords = "circus show entertainment" },
        new()
        {
            Symbol = "🎟️", Name = "Admission Tickets", HtmlCode = "&#127915;&#65039;", Category = "Activities", Keywords = "tickets event cinema concert"
        },
        new() { Symbol = "🎫", Name = "Ticket", HtmlCode = "&#127903;", Category = "Activities", Keywords = "ticket entry pass" },
        new() { Symbol = "🎬", Name = "Clapper Board", HtmlCode = "&#127916;", Category = "Activities", Keywords = "movie film action" },
        new() { Symbol = "🎤", Name = "Microphone", HtmlCode = "&#127908;", Category = "Activities", Keywords = "sing karaoke voice music" },
        new() { Symbol = "🎧", Name = "Headphone", HtmlCode = "&#127911;", Category = "Activities", Keywords = "headphones listen audio music" },
        new() { Symbol = "🎼", Name = "Musical Score", HtmlCode = "&#127932;", Category = "Activities", Keywords = "music score notes sheet" },
        new() { Symbol = "🎵", Name = "Musical Note", HtmlCode = "&#127925;", Category = "Activities", Keywords = "music note sound" },
        new() { Symbol = "🎶", Name = "Musical Notes", HtmlCode = "&#127926;", Category = "Activities", Keywords = "music notes melody" },
        new()
        {
            Symbol = "🎙️", Name = "Studio Microphone", HtmlCode = "&#127897;&#65039;", Category = "Activities", Keywords = "studio microphone podcast music"
        },
        new() { Symbol = "🎚️", Name = "Level Slider", HtmlCode = "&#127898;&#65039;", Category = "Activities", Keywords = "audio level slider music" },
        new()
        {
            Symbol = "🎛️", Name = "Control Knobs", HtmlCode = "&#127899;&#65039;", Category = "Activities", Keywords = "control knobs mixer studio music"
        },
        new() { Symbol = "🎹", Name = "Musical Keyboard", HtmlCode = "&#127929;", Category = "Activities", Keywords = "piano keyboard music" },
        new() { Symbol = "🥁", Name = "Drum", HtmlCode = "&#129345;", Category = "Activities", Keywords = "drum beat rhythm music" },
        new() { Symbol = "🪘", Name = "Long Drum", HtmlCode = "&#129696;", Category = "Activities", Keywords = "drum percussion rhythm" },
        new() { Symbol = "🎷", Name = "Saxophone", HtmlCode = "&#127927;", Category = "Activities", Keywords = "saxophone jazz music" },
        new() { Symbol = "🎺", Name = "Trumpet", HtmlCode = "&#127930;", Category = "Activities", Keywords = "trumpet brass music" },
        new() { Symbol = "🎸", Name = "Guitar", HtmlCode = "&#127928;", Category = "Activities", Keywords = "guitar rock music" },
        new() { Symbol = "🪕", Name = "Banjo", HtmlCode = "&#129693;", Category = "Activities", Keywords = "banjo strings music" },
        new() { Symbol = "🎻", Name = "Violin", HtmlCode = "&#127931;", Category = "Activities", Keywords = "violin strings orchestra music" },
        new() { Symbol = "📷", Name = "Camera", HtmlCode = "&#128247;", Category = "Activities", Keywords = "camera photo picture" },
        new() { Symbol = "🏆", Name = "Trophy", HtmlCode = "&#127942;", Category = "Activities", Keywords = "trophy award winner sport" },
        new() { Symbol = "🥇", Name = "1st Place Medal", HtmlCode = "&#129351;", Category = "Activities", Keywords = "gold medal first winner" },
        new() { Symbol = "🥈", Name = "2nd Place Medal", HtmlCode = "&#129352;", Category = "Activities", Keywords = "silver medal second" },
        new() { Symbol = "🥉", Name = "3rd Place Medal", HtmlCode = "&#129353;", Category = "Activities", Keywords = "bronze medal third" },
        new() { Symbol = "🏅", Name = "Sports Medal", HtmlCode = "&#127941;", Category = "Activities", Keywords = "sports medal award" },
        new() { Symbol = "🎖️", Name = "Military Medal", HtmlCode = "&#127894;&#65039;", Category = "Activities", Keywords = "medal honor ribbon" },
        new() { Symbol = "🎗️", Name = "Reminder Ribbon", HtmlCode = "&#127895;&#65039;", Category = "Activities", Keywords = "ribbon awareness symbol" },
        new() { Symbol = "🎽", Name = "Running Shirt", HtmlCode = "&#127933;", Category = "Activities", Keywords = "running shirt athletics sport" },
        new() { Symbol = "🛹", Name = "Skateboard", HtmlCode = "&#128761;", Category = "Activities", Keywords = "skateboard street sport" },
        new() { Symbol = "🛼", Name = "Roller Skate", HtmlCode = "&#128764;", Category = "Activities", Keywords = "roller skate skating sport" },
        new() { Symbol = "🛷", Name = "Sled", HtmlCode = "&#128755;", Category = "Activities", Keywords = "sled snow winter activity" },
        new() { Symbol = "⛸️", Name = "Ice Skate", HtmlCode = "&#9976;&#65039;", Category = "Activities", Keywords = "ice skate skating sport" },
        new() { Symbol = "🥌", Name = "Curling Stone", HtmlCode = "&#129356;", Category = "Activities", Keywords = "curling stone ice sport" },
        new() { Symbol = "🎿", Name = "Skis", HtmlCode = "&#127935;", Category = "Activities", Keywords = "skis snow sport" },
        new() { Symbol = "⛷️", Name = "Skier", HtmlCode = "&#9975;&#65039;", Category = "Activities", Keywords = "skier ski snow sport" },
        new() { Symbol = "🏂", Name = "Snowboarder", HtmlCode = "&#127938;", Category = "Activities", Keywords = "snowboarder snow sport" },
        new() { Symbol = "🏌️", Name = "Person Golfing", HtmlCode = "&#127948;&#65039;", Category = "Activities", Keywords = "golf golfer swing sport" },
        new() { Symbol = "🏇", Name = "Horse Racing", HtmlCode = "&#127943;", Category = "Activities", Keywords = "horse racing jockey sport" },
        new() { Symbol = "⛹️", Name = "Person Bouncing Ball", HtmlCode = "&#9977;&#65039;", Category = "Activities", Keywords = "basketball dribble sport" },
        new()
        {
            Symbol = "🏋️", Name = "Person Lifting Weights", HtmlCode = "&#127947;&#65039;", Category = "Activities", Keywords = "lifting weights gym fitness"
        },
        new() { Symbol = "🤼", Name = "People Wrestling", HtmlCode = "&#129340;", Category = "Activities", Keywords = "wrestling match sport" },
        new() { Symbol = "🤸", Name = "Person Cartwheeling", HtmlCode = "&#129336;", Category = "Activities", Keywords = "cartwheel gymnastics activity" },
        new()
        {
            Symbol = "⛹️‍♀️", Name = "Woman Bouncing Ball", HtmlCode = "&#9977;&#65039;&#8205;&#9792;&#65039;", Category = "Activities",
            Keywords = "woman basketball dribble sport"
        },
        new()
        {
            Symbol = "⛹️‍♂️", Name = "Man Bouncing Ball", HtmlCode = "&#9977;&#65039;&#8205;&#9794;&#65039;", Category = "Activities",
            Keywords = "man basketball dribble sport"
        },
        new() { Symbol = "🤺", Name = "Person Fencing", HtmlCode = "&#129338;", Category = "Activities", Keywords = "fencing sword duel sport" },
        new() { Symbol = "🤾", Name = "Person Playing Handball", HtmlCode = "&#129342;", Category = "Activities", Keywords = "handball throw sport" },
        new() { Symbol = "🏄", Name = "Person Surfing", HtmlCode = "&#127940;", Category = "Activities", Keywords = "surfing wave ocean sport" },
        new() { Symbol = "🏊", Name = "Person Swimming", HtmlCode = "&#127946;", Category = "Activities", Keywords = "swimming pool water sport" },
        new() { Symbol = "🤽", Name = "Person Playing Water Polo", HtmlCode = "&#129341;", Category = "Activities", Keywords = "water polo swim sport" },
        new() { Symbol = "🚣", Name = "Person Rowing Boat", HtmlCode = "&#128675;", Category = "Activities", Keywords = "rowing boat water sport" },
        new() { Symbol = "🧗", Name = "Person Climbing", HtmlCode = "&#129495;", Category = "Activities", Keywords = "climbing rock mountain sport" },
        new() { Symbol = "🚴", Name = "Person Biking", HtmlCode = "&#128692;", Category = "Activities", Keywords = "biking bicycle cycling sport" },
        new() { Symbol = "🚵", Name = "Person Mountain Biking", HtmlCode = "&#128693;", Category = "Activities", Keywords = "mountain biking cycling sport" },
        new() { Symbol = "🤹", Name = "Person Juggling", HtmlCode = "&#129337;", Category = "Activities", Keywords = "juggling circus performance skill" },
        new() { Symbol = "🏀", Name = "Basketball", HtmlCode = "&#127936;", Category = "Activities", Keywords = "basketball sport game" },
        new() { Symbol = "⚽", Name = "Soccer Ball", HtmlCode = "&#9917;", Category = "Activities", Keywords = "soccer football sport" },
        new() { Symbol = "⚾", Name = "Baseball", HtmlCode = "&#9918;", Category = "Activities", Keywords = "baseball sport ball" },
        new() { Symbol = "🥎", Name = "Softball", HtmlCode = "&#129358;", Category = "Activities", Keywords = "softball sport ball" },
        new() { Symbol = "🏐", Name = "Volleyball", HtmlCode = "&#127952;", Category = "Activities", Keywords = "volleyball sport ball" },
        new() { Symbol = "🏈", Name = "American Football", HtmlCode = "&#127944;", Category = "Activities", Keywords = "football sport nfl" },
        new() { Symbol = "🏉", Name = "Rugby Football", HtmlCode = "&#127945;", Category = "Activities", Keywords = "rugby football sport" },
        new() { Symbol = "🎾", Name = "Tennis", HtmlCode = "&#127934;", Category = "Activities", Keywords = "tennis racket sport" },
        new() { Symbol = "🥏", Name = "Flying Disc", HtmlCode = "&#129359;", Category = "Activities", Keywords = "frisbee flying disc sport" },
        new() { Symbol = "🏓", Name = "Ping Pong", HtmlCode = "&#127955;", Category = "Activities", Keywords = "ping pong table tennis" },
        new() { Symbol = "🏸", Name = "Badminton", HtmlCode = "&#127992;", Category = "Activities", Keywords = "badminton shuttlecock sport" },
        new() { Symbol = "🥍", Name = "Lacrosse", HtmlCode = "&#129357;", Category = "Activities", Keywords = "lacrosse stick sport" },
        new() { Symbol = "🏏", Name = "Cricket Game", HtmlCode = "&#127951;", Category = "Activities", Keywords = "cricket bat sport" },
        new() { Symbol = "🏑", Name = "Field Hockey", HtmlCode = "&#127953;", Category = "Activities", Keywords = "field hockey stick sport" },
        new() { Symbol = "🏒", Name = "Ice Hockey", HtmlCode = "&#127954;", Category = "Activities", Keywords = "ice hockey puck sport" },
        new() { Symbol = "🥊", Name = "Boxing Glove", HtmlCode = "&#129354;", Category = "Activities", Keywords = "boxing glove fight sport" },
        new() { Symbol = "🥋", Name = "Martial Arts Uniform", HtmlCode = "&#129355;", Category = "Activities", Keywords = "martial arts uniform karate judo" },
        new() { Symbol = "🥅", Name = "Goal Net", HtmlCode = "&#129349;", Category = "Activities", Keywords = "goal net soccer hockey" },
        new() { Symbol = "⛳", Name = "Flag In Hole", HtmlCode = "&#9971;", Category = "Activities", Keywords = "golf hole flag sport" },
        new() { Symbol = "🎣", Name = "Fishing Pole", HtmlCode = "&#127907;", Category = "Activities", Keywords = "fishing pole sport hobby" },
        new() { Symbol = "🤿", Name = "Diving Mask", HtmlCode = "&#129343;", Category = "Activities", Keywords = "diving mask swim snorkel" },
        new() { Symbol = "🪀", Name = "Yo-Yo", HtmlCode = "&#129664;", Category = "Activities", Keywords = "yo-yo toy trick play" },
        new() { Symbol = "🪁", Name = "Kite", HtmlCode = "&#129665;", Category = "Activities", Keywords = "kite fly play wind" },

        new() { Symbol = "📈", Name = "Chart Increasing", HtmlCode = "&#128200;", Category = "Business", Keywords = "chart growth business analytics" },
        new() { Symbol = "📉", Name = "Chart Decreasing", HtmlCode = "&#128201;", Category = "Business", Keywords = "chart decline analytics" },
        new() { Symbol = "📊", Name = "Bar Chart", HtmlCode = "&#128202;", Category = "Business", Keywords = "bar chart report" },
        new() { Symbol = "💼", Name = "Briefcase", HtmlCode = "&#128188;", Category = "Business", Keywords = "briefcase work office" },
        new() { Symbol = "🧾", Name = "Receipt", HtmlCode = "&#129534;", Category = "Business", Keywords = "receipt finance bill" },
        new() { Symbol = "💳", Name = "Credit Card", HtmlCode = "&#128179;", Category = "Business", Keywords = "credit card payment" },
        new() { Symbol = "💰", Name = "Money Bag", HtmlCode = "&#128176;", Category = "Business", Keywords = "money finance budget" },
        new() { Symbol = "🪙", Name = "Coin", HtmlCode = "&#129689;", Category = "Business", Keywords = "coin payment finance" },
        new() { Symbol = "🏦", Name = "Bank", HtmlCode = "&#127974;", Category = "Business", Keywords = "bank finance building" },
        new() { Symbol = "🧮", Name = "Abacus", HtmlCode = "&#129518;", Category = "Business", Keywords = "abacus count accounting" },
        new() { Symbol = "📅", Name = "Calendar", HtmlCode = "&#128197;", Category = "Business", Keywords = "calendar schedule date" },
        new() { Symbol = "🗓️", Name = "Spiral Calendar", HtmlCode = "&#128467;&#65039;", Category = "Business", Keywords = "calendar spiral planner" },
        new() { Symbol = "📆", Name = "Tear-Off Calendar", HtmlCode = "&#128198;", Category = "Business", Keywords = "calendar day schedule" },
        new() { Symbol = "⏰", Name = "Alarm Clock", HtmlCode = "&#9200;", Category = "Business", Keywords = "time reminder clock" },
        new() { Symbol = "⌛", Name = "Hourglass Done", HtmlCode = "&#8987;", Category = "Business", Keywords = "hourglass time deadline" },
        new() { Symbol = "⏳", Name = "Hourglass Not Done", HtmlCode = "&#9203;", Category = "Business", Keywords = "hourglass waiting time" },
        new() { Symbol = "🕒", Name = "Three O’Clock", HtmlCode = "&#128339;", Category = "Business", Keywords = "time clock hour" },
        new() { Symbol = "📨", Name = "Incoming Envelope", HtmlCode = "&#128232;", Category = "Business", Keywords = "mail inbox message" },
        new() { Symbol = "✉️", Name = "Envelope", HtmlCode = "&#9993;&#65039;", Category = "Business", Keywords = "mail envelope contact" },
        new() { Symbol = "📬", Name = "Open Mailbox With Raised Flag", HtmlCode = "&#128236;", Category = "Business", Keywords = "mail post message" },
        new() { Symbol = "🔍", Name = "Magnifying Glass Tilted Left", HtmlCode = "&#128269;", Category = "Business", Keywords = "search magnify inspect" },
        new() { Symbol = "🔎", Name = "Magnifying Glass Tilted Right", HtmlCode = "&#128270;", Category = "Business", Keywords = "search zoom inspect" },
        new() { Symbol = "🧭", Name = "Compass", HtmlCode = "&#129517;", Category = "Business", Keywords = "compass direction strategy" },
        new() { Symbol = "🗺️", Name = "World Map", HtmlCode = "&#128506;&#65039;", Category = "Business", Keywords = "map strategy planning" },
        new() { Symbol = "📋", Name = "Clipboard", HtmlCode = "&#128203;", Category = "Business", Keywords = "clipboard checklist office" },
        new() { Symbol = "📁", Name = "File Folder", HtmlCode = "&#128193;", Category = "Business", Keywords = "folder files work" },
        new() { Symbol = "📂", Name = "Open File Folder", HtmlCode = "&#128194;", Category = "Business", Keywords = "folder open files" }
    ];
}
