<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>12</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Api.Requests.Abstractions\Api.Requests.Abstractions.csproj" />
  </ItemGroup>

</Project>
