<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12</LangVersion>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AspNetCore.ApiControllers.Abstractions\AspNetCore.ApiControllers.Abstractions.csproj" />
      <ProjectReference Include="..\Domain.Abstractions\Domain.Abstractions.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.Orm\TimeTracker.Business.Orm.csproj" />
      <ProjectReference Include="..\TimeTracker.Business\TimeTracker.Business.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Bogus" Version="35.6.3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Core\" />
    </ItemGroup>

</Project>
