<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>12</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <WarningsAsErrors>CS0168,CS8602,CS0169,CS1998</WarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Production' ">
        <DefineConstants>TRACE;IS_RELEASE_BUILD;IS_WEB_APP</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DefineConstants>TRACE;IS_RELEASE_BUILD;IS_WEB_APP</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Development' ">
        <DefineConstants>TRACE;IS_DEVELOPMENT_BUILD;IS_WEB_APP</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Local' ">
        <DefineConstants>TRACE;IS_LOCAL_BUILD;IS_WEB_APP</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DefineConstants>TRACE;IS_WEB_APP</DefineConstants>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Blazor-ApexCharts" Version="6.1.0" />
        <PackageReference Include="blazor-dragdrop" Version="2.6.1" />
        <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
        <PackageReference Include="Fluxor.Blazor.Web" Version="6.9.0" />
        <PackageReference Include="LumexUI" Version="2.3.2" />
        <PackageReference Include="Majorsoft.Blazor.WebAssembly.Logging.Console" Version="1.5.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.5" PrivateAssets="all" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.5" />
        <PackageReference Include="Microsoft.DotNet.HotReload.WebAssembly.Browser" Version="10.0.201" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.14.0" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.14.0" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.16.0" />
        <PackageReference Include="System.Net.Http.Json" Version="10.0.5" />
        <PackageReference Include="System.Reactive.Linq" Version="6.1.0" />
        <PackageReference Include="Toolbelt.Blazor.HttpClientInterceptor" Version="10.2.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="wwwroot\appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="wwwroot\appsettings.Development.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="Shared\Components\Storage\FileUploader.razor.less">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="wwwroot\appsettings.Release.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="wwwroot\appsettings.Debug.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="Shared\Components\Form\MarkdownEdit.razor.less">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Remove="Pages\Dashboard\Calendar\CalendarPage.razor" />
      <Content Remove="Shared\Components\Form\TimeInput.razor" />
      <Content Remove="Shared\Components\Form\YesNoDropDown.razor" />
      <Content Remove="Store\GoalsTracker\**" />
      <Content Remove="Pages\Dashboard\Dashboard\**" />
      <Content Remove="Pages\Dashboard\GoalsTracker\**" />
      <Content Remove="Pages\Dashboard\Integrations\**" />
      <Content Remove="Pages\Dashboard\Members\**" />
      <Content Remove="Pages\Dashboard\Shared\NotificationCenter\**" />
      <Content Remove="Pages\Dashboard\Tag\**" />
      <Content Remove="Ignore\GoalsTracker\Parts\AddGoalModalForm.razor" />
      <Content Remove="Ignore\GoalsTracker\Parts\ChangePositionModal.razor" />
      <Content Remove="Ignore\GoalsTracker\Parts\GoalsTrackerTable.razor" />
      <Content Remove="Ignore\GoalsTracker\Parts\UpdateGoalModalForm.razor" />
      <Content Remove="Ignore\GoalsTracker\GoalsTrackerPage.razor" />
      <Content Remove="Ignore\Members\Parts\**" />
      <Content Remove="Ignore\Members\MembersPage.razor" />
      <Content Remove="Ignore\Integrations\Parts\**" />
      <Content Remove="Ignore\Integrations\IntegrationsPage.razor" />
      <Content Remove="Ui\Pages\Dashboard\Shared\NotificationCenter\Parts\ReminderCard.razor" />
      <Content Remove="Ui\Pages\Dashboard\Shared\NotificationCenter\**" />
      <Content Remove="Ui\Pages\Dashboard\Tag\Parts\TagsList.razor" />
      <Content Remove="Ui\Pages\Dashboard\Tag\Parts\AddTagModal.razor" />
      <Content Remove="Ui\Pages\Dashboard\Tag\**" />
      <Content Remove="Ui\Shared\Components\Form\TimeInput.razor" />
      <Content Remove="Ui\Shared\Components\Form\YesNoDropDown.razor" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TimeTracker.Api.Shared\TimeTracker.Api.Shared.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.Extensions\TimeTracker.Business.Extensions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Ignore\" />
      <Folder Include="Ignore\Dashboard\" />
      <Folder Include="Ignore\GoalsTracker\Parts\" />
      <Folder Include="Ignore\Integrations\" />
      <Folder Include="Ignore\Members\" />
      <Folder Include="Store\Dashboard\Effects\" />
      <Folder Include="Ui\" />
      <Folder Include="wwwroot\css\" />
      <Folder Include="wwwroot\img\logo\black" />
      <Folder Remove="node_modules" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Services\UI\DragAndDropService.cs" />
      <Compile Remove="Pages\Dashboard\Calendar\CalendarPage.razor.cs" />
      <Compile Remove="Shared\Components\Form\TimeInput.razor.cs" />
      <Compile Remove="Shared\Components\Form\YesNoDropDown.razor.cs" />
      <Compile Remove="Services\UI\ModalDialogProviderService.GoalsTracker.cs" />
      <Compile Remove="Services\UI\ModalDialogProviderService.NotificationsCenter.cs" />
      <Compile Remove="Services\UI\ModalDialogProviderService.Tags.cs" />
      <Compile Remove="Services\UI\ModalDialogProviderService.WorkspaceMembership.cs" />
      <Compile Remove="Store\GoalsTracker\**" />
      <Compile Remove="Pages\Dashboard\Dashboard\**" />
      <Compile Remove="Pages\Dashboard\GoalsTracker\**" />
      <Compile Remove="Pages\Dashboard\Integrations\**" />
      <Compile Remove="Pages\Dashboard\Members\**" />
      <Compile Remove="Pages\Dashboard\Shared\NotificationCenter\**" />
      <Compile Remove="Pages\Dashboard\Tag\**" />
    <Compile Remove="Pages\Dashboard\Shared\Components\Storage\FileView.razor.cs" />
    <Compile Remove="Ignore\GoalsTracker\Parts\AddGoalModalForm.razor.cs" />
    <Compile Remove="Ignore\GoalsTracker\Parts\ChangePositionModal.razor.cs" />
    <Compile Remove="Ignore\GoalsTracker\Parts\GoalsTrackerTable.razor.cs" />
    <Compile Remove="Ignore\GoalsTracker\Parts\UpdateGoalModalForm.razor.cs" />
    <Compile Remove="Ignore\GoalsTracker\GoalsTrackerPage.razor.cs" />
    <Compile Remove="Ignore\Members\Parts\**" />
    <Compile Remove="Ignore\Members\MembersPage.razor.cs" />
    <Compile Remove="Ignore\Integrations\Parts\**" />
    <Compile Remove="Ignore\Integrations\IntegrationsPage.razor.cs" />
    <Compile Remove="Ui\Pages\Dashboard\Shared\NotificationCenter\Parts\ReminderCard.razor.cs" />
    <Compile Remove="Ui\Pages\Dashboard\Shared\NotificationCenter\**" />
    <Compile Remove="Ui\Pages\Dashboard\Tag\Parts\TagsList.razor.cs" />
    <Compile Remove="Ui\Pages\Dashboard\Tag\Parts\AddTagModal.razor.cs" />
    <Compile Remove="Ui\Pages\Dashboard\Tag\**" />
    <Compile Remove="Ui\Shared\Components\Form\TimeInput.razor.cs" />
    <Compile Remove="Ui\Shared\Components\Form\YesNoDropDown.razor.cs" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Store\GoalsTracker\**" />
      <EmbeddedResource Remove="Pages\Dashboard\Dashboard\**" />
      <EmbeddedResource Remove="Pages\Dashboard\GoalsTracker\**" />
      <EmbeddedResource Remove="Pages\Dashboard\Integrations\**" />
      <EmbeddedResource Remove="Pages\Dashboard\Members\**" />
      <EmbeddedResource Remove="Pages\Dashboard\Shared\NotificationCenter\**" />
      <EmbeddedResource Remove="Pages\Dashboard\Tag\**" />
      <EmbeddedResource Remove="Ignore\Members\Parts\**" />
      <EmbeddedResource Remove="Ignore\Integrations\Parts\**" />
      <EmbeddedResource Remove="Ui\Pages\Dashboard\Shared\NotificationCenter\**" />
      <EmbeddedResource Remove="Ui\Pages\Dashboard\Tag\**" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Client\Parts\List\AddClientModal.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Client\Parts\List\ClientsList.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Dashboard\Index.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\GoalsTracker\GoalsTrackerPage.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\GoalsTracker\Parts\AddGoalModalForm.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\GoalsTracker\Parts\ChangePositionModal.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\GoalsTracker\Parts\GoalsTrackerTable.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\GoalsTracker\Parts\UpdateGoalModalForm.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Integrations\IntegrationsPage.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Integrations\Parts\ClickUpSettingsForm.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Integrations\Parts\JiraSettingsForm.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Integrations\Parts\RedmineSettingsForm.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Members\MembersPage.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Members\Parts\List\AddMemberModal.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Members\Parts\List\MembersList.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Members\Parts\MemberAccessModal.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Payment\Parts\AddPaymentModal.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Payment\Parts\List\PaymentsList.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Payment\Parts\UpdatePaymentModal.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Project\Parts\List\AddProjectModal.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Project\Parts\List\ProjectsList.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Project\Parts\List\UpdateProjectModal.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Report\PaymentReportPage.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Report\Summary\Parts\ByClientTable.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Report\Summary\Parts\ByDateTable.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Report\Summary\Parts\ByMonthTable.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Report\Summary\Parts\ByProjectTable.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Report\Summary\Parts\ByUserTable.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Report\Summary\Parts\ByWeekTable.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Report\Summary\Parts\FilterForm.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Report\Summary\Parts\SummaryInfoBlock.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Report\Summary\SummaryReportPage.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Report\TimeEntry\Parts\FilterForm.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Report\TimeEntry\TimeEntryPage.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\InitializationContainer.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\Layout.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\NavMenu.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\NotificationCenter\NotificationBadgeButton.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\NotificationCenter\NotificationCenterModal.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\NotificationCenter\Parts\ReminderCard.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\Tasks\AddTaskModalForm.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\Tasks\Comments\EditCommentForm.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\Tasks\Comments\TaskCommentsBlock.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\Tasks\TaskCard.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\Tasks\TaskIdBadge.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\Tasks\UpdateTaskForm.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\Tasks\UpdateTaskModal.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\TimeEntry\TimeEntryEditModal.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\TimeEntry\TimeEntryForm.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\TimeEntry\TimeEntryList.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Shared\TimeEntry\TimeEntryListModal.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Tag\Parts\AddTagModal.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Tag\Parts\TagsList.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Tag\Parts\UpdateTagModal.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Tag\TagsListPage.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Tasks\OverdueTasksPage.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Tasks\Parts\TasksFilterForm.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Tasks\Parts\TasksGrid.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Tasks\Parts\TasksListTree.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Tasks\Parts\TasksList\AddTasksListModalForm.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Tasks\Parts\TasksList\UpdateTasksListModalForm.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Tasks\Parts\TasksTable.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Tasks\TaskPage.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Tasks\TasksPage.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\TimeEntry\Parts\DurationField.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\TimeEntry\Parts\TimeCounterField.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\TimeEntry\TimeEntryPage.razor" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Workspace\WorkspacesPage.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\ClientsDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\EnumDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\MarkdownEdit.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\MembersDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\MultipleUsersDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\ProjectsDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\TagsDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\TaskListsDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\TimeInput.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\YesNoDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Storage\FilesList.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Storage\FileUploader.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Storage\FileView.razor" />
      <_ContentIncludedByDefault Remove="Pages\Landing\User\Password\ChangePassword.razor" />
      <_ContentIncludedByDefault Remove="Pages\Landing\User\Password\ResetPassword.razor" />
      <_ContentIncludedByDefault Remove="Pages\Landing\User\Registration\Step1.razor" />
      <_ContentIncludedByDefault Remove="Pages\Landing\User\Registration\Step2.razor" />
      <_ContentIncludedByDefault Remove="Ignore\Members\Parts\List\AddMemberModal.razor" />
      <_ContentIncludedByDefault Remove="Ignore\Members\Parts\List\MembersList.razor" />
      <_ContentIncludedByDefault Remove="Ignore\Members\Parts\MemberAccessModal.razor" />
      <_ContentIncludedByDefault Remove="Ignore\Integrations\Parts\ClickUpSettingsForm.razor" />
      <_ContentIncludedByDefault Remove="Ignore\Integrations\Parts\JiraSettingsForm.razor" />
      <_ContentIncludedByDefault Remove="Ignore\Integrations\Parts\RedmineSettingsForm.razor" />
      <_ContentIncludedByDefault Remove="Shared\BaseLayout.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Dialogs\ConfirmationDialog.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\Select\ClientsDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\Select\EnumDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\Select\MembersDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\Select\MultipleUsersDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\Select\ProjectsDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\Select\TagsDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\Select\TaskListsDropDown.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\TextField\DateTimeEditField.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Form\TextField\TimeEditField.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\Storage\FileViewModal.razor" />
      <_ContentIncludedByDefault Remove="Shared\Components\TagsBadgesList.razor" />
      <_ContentIncludedByDefault Remove="Shared\InitializationContainer.razor" />
      <_ContentIncludedByDefault Remove="Shared\MainHeader.razor" />
      <_ContentIncludedByDefault Remove="Ui\Pages\Dashboard\Shared\NotificationCenter\NotificationBadgeButton.razor" />
      <_ContentIncludedByDefault Remove="Ui\Pages\Dashboard\Shared\NotificationCenter\NotificationCenterModal.razor" />
      <_ContentIncludedByDefault Remove="Ui\Pages\Dashboard\Shared\NotificationCenter\Parts\ReminderCard.razor" />
      <_ContentIncludedByDefault Remove="Ui\Pages\Dashboard\Tag\Parts\AddTagModal.razor" />
      <_ContentIncludedByDefault Remove="Ui\Pages\Dashboard\Tag\Parts\TagsList.razor" />
      <_ContentIncludedByDefault Remove="Ui\Pages\Dashboard\Tag\Parts\UpdateTagModal.razor" />
      <_ContentIncludedByDefault Remove="Ui\Pages\Dashboard\Tag\TagsListPage.razor" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.bundle.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.bundle.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.bundle.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.bundle.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.esm.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.esm.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.esm.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.esm.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.min.js.map" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Ignore\GoalsTracker\Parts\GoalsTrackerTable.razor.less" />
      <None Remove="Ignore\Members\Parts\**" />
      <None Remove="Ignore\Integrations\Parts\**" />
      <None Include="wwwroot\lib\.gitignore" />
      <None Remove="Ui\Pages\Dashboard\Shared\NotificationCenter\**" />
      <None Remove="Ui\Pages\Dashboard\Tag\**" />
    </ItemGroup>

    <PropertyGroup>
        <TailwindInputCss>$(ProjectDir)styles\app.css</TailwindInputCss>
        <TailwindOutputCss>$(ProjectDir)wwwroot\css\app.min.css</TailwindOutputCss>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="styles/lumexui/**/*.*" />
        <Compile Remove="styles/lumexui/**/*.*" />
        <Content Remove="styles/lumexui/**/*.*" />
    </ItemGroup>

    <Target Name="Npm" BeforeTargets="Build" Condition="!Exists('node_modules')">
        <Message Text="Running npm ci..." Importance="high" />
        <Exec Command="npm install" />
    </Target>

    <Target Name="CompileLess" BeforeTargets="Build;PrepareForPublish">
        <ItemGroup>
            <LessFiles
                Include="Ui\**\*.less"
                Exclude="node_modules\**\*.less;wwwroot\**\*.less;styles\**\*.less;Ignore\**\*.less"
            />
        </ItemGroup>

        <Exec Command="node $(ProjectDir)node_modules/less/bin/lessc %(LessFiles.Identity) %(LessFiles.RelativeDir)%(Filename).css" />
    </Target>

    <Target Name="CopyLumexUi" BeforeTargets="Build">
        <ItemGroup>
            <Lumex Include="bin/lumexui/**/*.*" />
        </ItemGroup>
        <Message Text="Copying LumexUI theme files..." />

        <Copy
            SourceFiles="@(Lumex)"
            DestinationFolder="styles/lumexui"
            SkipUnchangedFiles="true" />

        <Message Text="Copied @(LumexCopied)" Importance="high" />
    </Target>
    
    <Target Name="TailwindCssBuild" AfterTargets="CopyLumexUi">
        <Message Text="Checking for Tailwind CLI for your OS..."/>
        <MakeDir Directories="$(TailwindToolsDir)" />

        <Message Text="Building Tailwind CSS..." />
        <Exec Command="npx @tailwindcss/cli -i $(TailwindInputCss) -o $(TailwindOutputCss)" />
    </Target>
</Project>
