<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>12</LangVersion>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DefineConstants>TRACE;IS_RELEASE_BUILD;IS_WEB_APP</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Development' ">
        <DefineConstants>TRACE;IS_DEVELOPMENT_BUILD;IS_WEB_APP</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DefineConstants>TRACE;IS_WEB_APP</DefineConstants>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Blazor-ApexCharts" Version="3.1.0" />
        <PackageReference Include="blazor-dragdrop" Version="2.6.1" />
        <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
        <PackageReference Include="Fluxor.Blazor.Web" Version="5.9.1" />
        <PackageReference Include="Majorsoft.Blazor.WebAssembly.Logging.Console" Version="1.5.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.3" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.3" PrivateAssets="all" />
        <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="8.0.3" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.5.0" />
        <PackageReference Include="MudBlazor" Version="6.19.1" />
        <PackageReference Include="System.Net.Http.Json" Version="8.0.0" />
        <PackageReference Include="System.Reactive.Linq" Version="6.0.0" />
        <PackageReference Include="Toolbelt.Blazor.HttpClientInterceptor" Version="10.2.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="wwwroot\appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="wwwroot\appsettings.Development.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Pages\Dashboard\Report\TimeEntry\Parts\FilterForm.razor.less">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="Shared\Components\Storage\FileUploader.razor.less">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Update="wwwroot\appsettings.Release.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="wwwroot\appsettings.Debug.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="Shared\Components\Form\MarkdownEdit.razor.less">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </Content>
      <Content Remove="Pages\Dashboard\Calendar\CalendarPage.razor" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TimeTracker.Api.Shared\TimeTracker.Api.Shared.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.Extensions\TimeTracker.Business.Extensions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Pages\Dashboard\Dashboard\Parts\" />
      <Folder Include="Store\Dashboard\Effects\" />
      <Folder Include="wwwroot\img\logo\black" />
    </ItemGroup>

    <ItemGroup>
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Services\UI\DragAndDropService.cs" />
      <Compile Remove="Pages\Dashboard\Calendar\CalendarPage.razor.cs" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\sample-data\weather.json" />
    </ItemGroup>

</Project>
