<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <WarningsAsErrors>CS0168,CS8602,CS0169,CS1998</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" Version="9.1.0" />
      <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.0" />
      <PackageReference Include="AutoMapper" Version="15.1.3" />
      <PackageReference Include="AWSSDK.S3" Version="4.0.23.3" />
      <PackageReference Include="Google.Cloud.Storage.V1" Version="4.14.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.8" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.8" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
      <PackageReference Include="Serilog" Version="4.3.1" />
      <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
      <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
      <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
      <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
      <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
      <PackageReference Include="Serilog.Expressions" Version="5.0.0" />
      <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
      <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
      <PackageReference Include="Serilog.Sinks.Graylog" Version="3.1.1" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AspNetCore.ApiControllers.Abstractions\AspNetCore.ApiControllers.Abstractions.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.Common\TimeTracker.Business.Common.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.Notifications\TimeTracker.Business.Notifications.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.Orm\TimeTracker.Business.Orm.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\UserResources.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>UserResources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\UserResources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>UserResources.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Mvc\Attribute\Validation\" />
    </ItemGroup>

</Project>
