<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Fluxor" Version="6.10.0" />
        <PackageReference Include="Fluxor.Blazor.Web" Version="6.10.0" />
        <PackageReference Include="LumexUI" Version="2.4.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.10" />
        <PackageReference Include="Toolbelt.Blazor.HttpClientInterceptor" Version="10.2.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TimeTracker.Api.Shared\TimeTracker.Api.Shared.csproj" />
        <ProjectReference Include="..\TimeTracker.Business.Common\TimeTracker.Business.Common.csproj" />
        <ProjectReference Include="..\TimeTracker.Business.Extensions\TimeTracker.Business.Extensions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Remove="Ui\Shared\Components\Form\TimeInput.razor" />
        <Content Remove="Ui\Shared\Components\Form\YesNoDropDown.razor" />
        <Compile Remove="Ui\Shared\Components\Form\TimeInput.razor.cs" />
        <Compile Remove="Ui\Shared\Components\Form\YesNoDropDown.razor.cs" />
    </ItemGroup>

</Project>
