<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Api.Requests.Base\Api.Requests.Base.csproj" />
      <ProjectReference Include="..\AspNetCore.ApiControllers.Extensions\AspNetCore.ApiControllers.Extensions.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.FileStorage.Commons\TimeTracker.Business.FileStorage.Commons.csproj" />
      <ProjectReference Include="..\TimeTracker.Business.FileStorage\TimeTracker.Business.FileStorage.csproj" />
      <ProjectReference Include="..\TimeTracker.Business\TimeTracker.Business.csproj" />
    </ItemGroup>

</Project>
